const API_URL=localStorage.getItem("wayneApiUrl")||window.WAYNE_API_URL||"http://localhost:5000",token=localStorage.getItem("wayneToken");
const $=id=>document.getElementById(id);
const message=$("message"),adminName=$("adminName"),adminTitle=$("adminTitle"),adminSidebar=$("adminSidebar"),adminMenuBtn=$("adminMenuBtn"),logoutButton=$("logoutButton"),statProducts=$("statProducts"),statOrders=$("statOrders"),statPaid=$("statPaid"),statRevenue=$("statRevenue"),adminProductTable=$("adminProductTable"),adminOrderTable=$("adminOrderTable"),adminUserTable=$("adminUserTable"),productForm=$("productForm"),productFormTitle=$("productFormTitle"),clearProduct=$("clearProduct"),refreshOrders=$("refreshOrders"),apiUrlInput=$("apiUrlInput"),saveApiUrl=$("saveApiUrl"),siteSettingsForm=$("siteSettingsForm"),announcementEnabled=$("announcementEnabled"),announcementTitle=$("announcementTitle"),announcementMessage=$("announcementMessage"),telegramUrl=$("telegramUrl"),p_id=$("p_id"),p_name=$("p_name"),p_platform=$("p_platform"),p_type=$("p_type"),p_price=$("p_price"),p_stock=$("p_stock"),p_icon=$("p_icon"),p_c1=$("p_c1"),p_c2=$("p_c2"),p_delivery=$("p_delivery"),p_status=$("p_status"),p_description=$("p_description"),p_private=$("p_private"),p_inventory=$("p_inventory"),platformPicker=$("platformPicker"),brandColorText=$("brandColorText"),inventoryAvailable=$("inventoryAvailable"),inventorySold=$("inventorySold"),inventoryLow=$("inventoryLow"),inventoryProducts=$("inventoryProducts"),inventoryManager=$("inventoryManager"),inventoryProductName=$("inventoryProductName"),inventoryProductMeta=$("inventoryProductMeta"),inventoryProductCount=$("inventoryProductCount"),inventoryHistory=$("inventoryHistory"),refreshInventory=$("refreshInventory"),restockForm=$("restockForm"),restockLines=$("restockLines"),restockButton=$("restockButton");
let products=[],orders=[],users=[],inventoryRows=[],selectedInventoryProduct="";
function money(n){return"₦"+Number(n||0).toLocaleString("en-NG")}function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}function show(t,type="error"){message.textContent=t;message.className="message "+type;message.style.display="block"}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:"Bearer "+token};const r=await fetch(API_URL+path,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
async function checkAdmin(){if(!token){location.replace("login.html");return false}try{const d=await api("/api/auth/admin");adminName.textContent=d.user.firstName+" "+d.user.lastName;return true}catch(e){location.replace("login.html");return false}}

const platformPresets=[
 {name:"YouTube",slug:"youtube",color1:"#FF0000",color2:"#CC0000",icon:"▶",type:"social"},
 {name:"Facebook",slug:"facebook",color1:"#1877F2",color2:"#0D5FC4",icon:"f",type:"social"},
 {name:"Instagram",slug:"instagram",color1:"#833AB4",color2:"#E1306C",icon:"◎",type:"social"},
 {name:"X",slug:"x",color1:"#000000",color2:"#343434",icon:"X",type:"social"},
 {name:"TikTok",slug:"tiktok",color1:"#000000",color2:"#25F4EE",icon:"♪",type:"social"},
 {name:"TikTok Ads",slug:"tiktok",color1:"#000000",color2:"#FE2C55",icon:"Ad",type:"social"},
 {name:"Snapchat",slug:"snapchat",color1:"#FFFC00",color2:"#F4D000",icon:"◉",type:"social"},
 {name:"Reddit",slug:"reddit",color1:"#FF4500",color2:"#D93A00",icon:"●",type:"social"},
 {name:"Discord",slug:"discord",color1:"#5865F2",color2:"#404EED",icon:"◈",type:"social"},
 {name:"WhatsApp",slug:"whatsapp",color1:"#25D366",color2:"#128C7E",icon:"◔",type:"social"},
 {name:"Telegram",slug:"telegram",color1:"#26A5E4",color2:"#168AC0",icon:"➤",type:"social"},
 {name:"LinkedIn",slug:"",color1:"#0A66C2",color2:"#004182",icon:"in",type:"social"},
 {name:"Pinterest",slug:"pinterest",color1:"#BD081C",color2:"#8C0615",icon:"P",type:"social"},
 {name:"Quora",slug:"quora",color1:"#B92B27",color2:"#8E211E",icon:"Q",type:"social"},
 {name:"GitHub",slug:"github",color1:"#181717",color2:"#444444",icon:"⌘",type:"social"},
 {name:"Spotify",slug:"spotify",color1:"#1ED760",color2:"#169C46",icon:"≋",type:"social"},
 {name:"Taimi",slug:"",color1:"#FF477E",color2:"#8D4AE8",icon:"♥",type:"social"},
 {name:"Grindr",slug:"",color1:"#FECB16",color2:"#E5A900",icon:"♜",type:"social"},
 {name:"Bumble",slug:"",color1:"#FFC629",color2:"#E6A800",icon:"⬡",type:"social"},
 {name:"MeetMe",slug:"",color1:"#16A8E2",color2:"#087FC4",icon:"♟",type:"social"},
 {name:"Badoo",slug:"badoo",color1:"#783BF9",color2:"#FF5A8B",icon:"B",type:"social"},
 {name:"Dating Apps",slug:"",color1:"#E83E8C",color2:"#9B51E0",icon:"♥",type:"social"},
 {name:"VPN",slug:"protonvpn",color1:"#6D4AFF",color2:"#372580",icon:"✓",type:"vpn"}
];
function presetKey(value){const key=String(value||"").trim().toLowerCase();return ["twitter","twitter / x","x.com"].includes(key)?"x":key}
function presetIcon(p){return p.slug?`<img src="https://cdn.simpleicons.org/${p.slug}/${p.color1.slice(1)}" alt="">`:`<span style="color:${p.color1}">${esc(p.icon)}</span>`}
function renderPlatformPicker(){platformPicker.innerHTML=platformPresets.map(p=>`<button type="button" class="admin-platform-option" data-platform-choice="${esc(p.name)}">${presetIcon(p)}<b>${esc(p.name)}</b><small>${p.type==="vpn"?"VPN":"Social"}</small></button>`).join("")}
function selectPlatform(name){const p=platformPresets.find(x=>presetKey(x.name)===presetKey(name));if(!p)return;p_platform.value=p.name;p_type.value=p.type;p_icon.value=p.icon;p_c1.value=p.color1;p_c2.value=p.color2;brandColorText.textContent=`${p.color1} · ${p.color2}`;document.querySelectorAll("[data-platform-choice]").forEach(b=>b.classList.toggle("selected",presetKey(b.dataset.platformChoice)===presetKey(p.name)))}
renderPlatformPicker();platformPicker.onclick=e=>{const b=e.target.closest("[data-platform-choice]");if(b)selectPlatform(b.dataset.platformChoice)};
document.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-section]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".admin-section").forEach(s=>s.classList.remove("active"));document.getElementById(b.dataset.section).classList.add("active");adminTitle.textContent=b.textContent.trim();adminSidebar.classList.remove("open");if(b.dataset.section==="inventory")loadInventoryOverview()});adminMenuBtn.onclick=()=>adminSidebar.classList.toggle("open");logoutButton.onclick=()=>{localStorage.removeItem("wayneToken");localStorage.removeItem("wayneUser");location.href="login.html"}
function stats(){statProducts.textContent=products.length;statOrders.textContent=orders.length;const paid=orders.filter(o=>o.paymentStatus==="paid");statPaid.textContent=paid.length;statRevenue.textContent=money(paid.reduce((s,o)=>s+Number(o.totalAmount||0),0))}
async function loadProducts(){const d=await api("/api/products/admin/all");products=d.products||[];adminProductTable.innerHTML=products.length?products.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.platform)}</small></td><td>${esc(p.type)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${esc(p.status)}</td><td><button class="ghost-btn" onclick="editProduct('${p._id}')">Edit</button> <button class="danger-btn" onclick="deleteProduct('${p._id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="6">No products.</td></tr>`;stats()}
async function loadOrders(){const d=await api("/api/orders/admin/all");orders=d.orders||[];adminOrderTable.innerHTML=orders.length?orders.map(o=>`<tr><td>${esc(o._id)}</td><td>${esc((o.user?.firstName||"")+" "+(o.user?.lastName||""))}<br><small>${esc(o.user?.email||"")}</small></td><td>${esc(o.productName)}</td><td>${money(o.totalAmount)}</td><td>${esc(o.paymentStatus)}</td><td><select class="filter-select" onchange="setOrderStatus('${o._id}',this.value)">${["pending","processing","completed","cancelled","refunded"].map(s=>`<option value="${s}" ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join(""):`<tr><td colspan="6">No orders.</td></tr>`;stats()}
async function loadUsers(){const d=await api("/api/auth/admin/users");users=d.users||[];adminUserTable.innerHTML=users.length?users.map(u=>`<tr><td>${esc(u.firstName+" "+u.lastName)}</td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${esc(u.role)}</td><td>${u.isActive?"Active":"Disabled"}</td></tr>`).join(""):`<tr><td colspan="5">No users.</td></tr>`}
async function loadSiteSettings(){const d=await api("/api/settings/admin"),s=d.settings||{};announcementEnabled.checked=!!s.announcementEnabled;announcementTitle.value=s.announcementTitle||"";announcementMessage.value=s.announcementMessage||"";telegramUrl.value=s.telegramUrl||""}
async function loadInventoryOverview(){try{const d=await api("/api/products/admin/inventory/overview");inventoryRows=d.inventory||[];inventoryAvailable.textContent=d.totals?.available||0;inventorySold.textContent=d.totals?.sold||0;inventoryLow.textContent=d.totals?.lowStock||0;inventoryProducts.innerHTML=inventoryRows.length?inventoryRows.map(p=>`<button type="button" class="inventory-product-card ${p.lowStock?"low":""} ${String(selectedInventoryProduct)===String(p.id)?"selected":""}" data-inventory-product="${esc(p.id)}"><span><strong>${esc(p.name)}</strong><small>${esc(p.platform)} · ${esc(p.status)}</small></span><span class="inventory-card-count"><b>${p.available}</b> available<small>${p.sold} sold</small></span>${p.lowStock?'<em>Low stock</em>':""}</button>`).join(""):'<div class="empty">No inventory-managed products yet.</div>';if(selectedInventoryProduct&&inventoryRows.some(p=>String(p.id)===String(selectedInventoryProduct)))await loadInventoryDetail(selectedInventoryProduct)}catch(e){show(e.message)}}
async function loadInventoryDetail(id){try{selectedInventoryProduct=id;const d=await api(`/api/products/admin/inventory/${encodeURIComponent(id)}`),p=d.product,items=d.items||[];inventoryManager.hidden=false;inventoryProductName.textContent=p.name;inventoryProductMeta.textContent=`${p.platform} · ${p.status}`;inventoryProductCount.textContent=`${p.stock} available`;inventoryHistory.innerHTML=items.length?items.map(i=>`<tr><td>${new Date(i.createdAt).toLocaleString()}</td><td><span class="inventory-status ${esc(i.status)}">${esc(i.status)}</span></td><td>${i.soldTo?`${esc((i.soldTo.firstName||"")+" "+(i.soldTo.lastName||""))}<br><small>${esc(i.soldTo.email||"")}</small>`:"—"}</td><td>${i.soldAt?new Date(i.soldAt).toLocaleString():"—"}</td><td>${i.order?esc(i.order):"—"}</td></tr>`).join(""):'<tr><td colspan="5">No inventory records.</td></tr>';document.querySelectorAll("[data-inventory-product]").forEach(b=>b.classList.toggle("selected",String(b.dataset.inventoryProduct)===String(id)))}catch(e){show(e.message)}}
inventoryProducts.onclick=e=>{const b=e.target.closest("[data-inventory-product]");if(b)loadInventoryDetail(b.dataset.inventoryProduct)};
refreshInventory.onclick=loadInventoryOverview;
restockForm.onsubmit=async e=>{e.preventDefault();if(!selectedInventoryProduct)return;const inventoryItems=restockLines.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!inventoryItems.length)return;restockButton.disabled=true;restockButton.textContent="Adding securely…";try{const d=await api(`/api/products/admin/inventory/${encodeURIComponent(selectedInventoryProduct)}/restock`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryItems})});restockForm.reset();show(`${d.added} new records added. ${d.duplicates} duplicates ignored.`,"success");await loadProducts();await loadInventoryOverview()}catch(e){show(e.message)}finally{restockButton.disabled=false;restockButton.textContent="Add Inventory Securely"}};
window.setOrderStatus=async(id,status)=>{try{await api(`/api/orders/admin/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await loadOrders()}catch(e){show(e.message)}}
function clearForm(){productForm.reset();p_id.value="";p_platform.value="";p_icon.value="";p_stock.value="0";p_c1.value="#1556c9";p_c2.value="#09a2df";p_delivery.value="instant";brandColorText.textContent="Select a platform";document.querySelectorAll("[data-platform-choice]").forEach(b=>b.classList.remove("selected"));productFormTitle.textContent="Add Product"}clearProduct.onclick=clearForm
window.editProduct=id=>{const p=products.find(x=>x._id===id);if(!p)return;p_id.value=p._id;p_name.value=p.name;selectPlatform(p.platform);if(!platformPresets.some(x=>presetKey(x.name)===presetKey(p.platform))){p_platform.value=p.platform;p_type.value=p.type;p_icon.value=p.icon||"";p_c1.value=p.color1||"#1556c9";p_c2.value=p.color2||"#09a2df";brandColorText.textContent=`${p_c1.value} · ${p_c2.value}`}p_price.value=p.price;p_stock.value=p.stock;p_delivery.value="instant";p_status.value=p.status;p_description.value=p.description||"";p_inventory.value="";p_inventory.placeholder=`${p.stock||0} unused records already saved. Paste new records here to add more.`;productFormTitle.textContent="Edit Product — add more inventory if needed";window.scrollTo({top:0,behavior:"smooth"})}
window.deleteProduct=async id=>{if(!confirm("Delete this product?"))return;try{await api("/api/products/"+id,{method:"DELETE"});await loadProducts()}catch(e){show(e.message)}}
productForm.onsubmit=async e=>{e.preventDefault();if(!p_platform.value){show("Choose a platform from the grid first.");platformPicker.scrollIntoView({behavior:"smooth",block:"center"});return}const id=p_id.value,inventoryItems=p_inventory.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!id&&!inventoryItems.length){show("Paste at least one unique delivery record, one per line.");p_inventory.focus();return}const body={name:p_name.value.trim(),platform:p_platform.value.trim(),type:p_type.value,price:Number(p_price.value),icon:p_icon.value.trim(),color1:p_c1.value,color2:p_c2.value,deliveryType:"instant",inventoryManaged:true,inventoryItems,status:p_status.value,description:p_description.value.trim(),privateDelivery:""};try{await api(id?"/api/products/"+id:"/api/products",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});clearForm();await loadProducts();show(`Product saved. ${inventoryItems.length?inventoryItems.length+" inventory lines processed.":"Existing inventory preserved."}`,"success")}catch(e){show(e.message)}}
siteSettingsForm.onsubmit=async e=>{e.preventDefault();try{await api("/api/settings/admin",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({announcementEnabled:announcementEnabled.checked,announcementTitle:announcementTitle.value,announcementMessage:announcementMessage.value,telegramUrl:telegramUrl.value})});show("Announcement and Telegram settings saved.","success")}catch(e){show(e.message)}};
refreshOrders.onclick=loadOrders;apiUrlInput.value=API_URL;saveApiUrl.onclick=()=>{localStorage.setItem("wayneApiUrl",apiUrlInput.value.replace(/\/$/,""));location.reload()};(async()=>{if(!(await checkAdmin()))return;try{await Promise.all([loadProducts(),loadOrders(),loadUsers(),loadSiteSettings()])}catch(e){show(e.message)}})();
