const API_URL=localStorage.getItem("wayneApiUrl")||window.WAYNE_API_URL||"http://localhost:5000",token=localStorage.getItem("wayneToken");
const $=id=>document.getElementById(id);
const message=$("message"),adminName=$("adminName"),adminTitle=$("adminTitle"),adminSidebar=$("adminSidebar"),adminMenuBtn=$("adminMenuBtn"),logoutButton=$("logoutButton"),statProducts=$("statProducts"),statOrders=$("statOrders"),statPaid=$("statPaid"),statRevenue=$("statRevenue"),adminProductTable=$("adminProductTable"),adminOrderTable=$("adminOrderTable"),adminUserTable=$("adminUserTable"),productForm=$("productForm"),productFormTitle=$("productFormTitle"),clearProduct=$("clearProduct"),refreshOrders=$("refreshOrders"),apiUrlInput=$("apiUrlInput"),saveApiUrl=$("saveApiUrl"),siteSettingsForm=$("siteSettingsForm"),announcementEnabled=$("announcementEnabled"),announcementTitle=$("announcementTitle"),announcementMessage=$("announcementMessage"),telegramUrl=$("telegramUrl"),p_id=$("p_id"),p_name=$("p_name"),p_platform=$("p_platform"),p_type=$("p_type"),p_price=$("p_price"),p_stock=$("p_stock"),p_icon=$("p_icon"),p_c1=$("p_c1"),p_c2=$("p_c2"),p_delivery=$("p_delivery"),p_status=$("p_status"),p_description=$("p_description"),p_private=$("p_private"),p_inventory=$("p_inventory"),platformPicker=$("platformPicker"),brandColorText=$("brandColorText"),inventoryAvailable=$("inventoryAvailable"),inventorySold=$("inventorySold"),inventoryLow=$("inventoryLow"),inventoryProducts=$("inventoryProducts"),inventoryManager=$("inventoryManager"),inventoryProductName=$("inventoryProductName"),inventoryProductMeta=$("inventoryProductMeta"),inventoryProductCount=$("inventoryProductCount"),inventoryHistory=$("inventoryHistory"),refreshInventory=$("refreshInventory"),restockForm=$("restockForm"),restockLines=$("restockLines"),restockButton=$("restockButton"),supportOpen=$("supportOpen"),supportProgress=$("supportProgress"),supportResolved=$("supportResolved"),adminTicketList=$("adminTicketList"),refreshSupport=$("refreshSupport"),adminConversation=$("adminConversation"),adminConversationTitle=$("adminConversationTitle"),adminConversationMeta=$("adminConversationMeta"),adminConversationMessages=$("adminConversationMessages"),adminTicketStatus=$("adminTicketStatus"),adminReplyForm=$("adminReplyForm"),adminReplyMessage=$("adminReplyMessage"),resolveWithReply=$("resolveWithReply"),adminReplyButton=$("adminReplyButton");
let products=[],orders=[],users=[],inventoryRows=[],selectedInventoryProduct="",supportTickets=[],selectedSupportTicket="",editingProductId="",productSaveBusy=false;
const adminAuditTable=$("adminAuditTable"),auditSearch=$("auditSearch"),auditEntity=$("auditEntity"),searchAudit=$("searchAudit"),refreshAudit=$("refreshAudit");
const passwordSearchForm=$("passwordSearchForm"),passwordHelpEmail=$("passwordHelpEmail"),passwordSearchButton=$("passwordSearchButton"),passwordCustomerResult=$("passwordCustomerResult"),passwordCustomerName=$("passwordCustomerName"),passwordCustomerMeta=$("passwordCustomerMeta"),temporaryPasswordForm=$("temporaryPasswordForm"),passwordHelpAdminPassword=$("passwordHelpAdminPassword"),temporaryPasswordButton=$("temporaryPasswordButton"),temporaryPasswordResult=$("temporaryPasswordResult"),temporaryPasswordValue=$("temporaryPasswordValue"),copyTemporaryPassword=$("copyTemporaryPassword");let passwordHelpCustomerEmail="";
const guidedInventoryList=$("guidedInventoryList"),guidedInventoryCount=$("guidedInventoryCount"),addInventoryRecord=$("addInventoryRecord");
const reportRevenue=$("reportRevenue"),reportPaid=$("reportPaid"),reportOrders=$("reportOrders"),reportAverage=$("reportAverage"),reportPaidRate=$("reportPaidRate"),reportPeriodLabel=$("reportPeriodLabel"),reportFrom=$("reportFrom"),reportTo=$("reportTo"),applyReportDates=$("applyReportDates"),exportSalesCsv=$("exportSalesCsv"),revenueChart=$("revenueChart"),reportStatuses=$("reportStatuses"),reportProducts=$("reportProducts"),reportPlatforms=$("reportPlatforms"),reportSalesTable=$("reportSalesTable");let reportDateRange=30,reportCustomDates=null;
const refundSearch=$("refundSearch"),refundEligibleCount=$("refundEligibleCount"),refundOrderList=$("refundOrderList"),refreshRefunds=$("refreshRefunds"),refundConfirmPanel=$("refundConfirmPanel"),refundOrderTitle=$("refundOrderTitle"),refundOrderMeta=$("refundOrderMeta"),refundOrderAmount=$("refundOrderAmount"),refundForm=$("refundForm"),refundReason=$("refundReason"),refundAdminPassword=$("refundAdminPassword"),refundAcknowledgement=$("refundAcknowledgement"),refundSubmitButton=$("refundSubmitButton"),refundHistoryTable=$("refundHistoryTable");let selectedRefundOrder="",refundTransactions=[];
const refreshSecurity=$("refreshSecurity"),securityFailedPayments=$("securityFailedPayments"),securityCancelledOrders=$("securityCancelledOrders"),securityRefundsToday=$("securityRefundsToday"),securityAdminCredits=$("securityAdminCredits"),securityScore=$("securityScore"),securityProtectionList=$("securityProtectionList"),securityEventTable=$("securityEventTable");
const overviewPendingPayments=$("overviewPendingPayments"),overviewLowStock=$("overviewLowStock"),overviewOpenSupport=$("overviewOpenSupport"),overviewPendingOrders=$("overviewPendingOrders"),refreshOverview=$("refreshOverview");
function money(n){return"₦"+Number(n||0).toLocaleString("en-NG")}function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}function show(t,type="error"){message.textContent=t;message.className="message "+type;message.style.display="block"}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:"Bearer "+token};const r=await fetch(API_URL+path,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
async function checkAdmin(){if(!token){location.replace("login.html");return false}try{const d=await api("/api/auth/admin");adminName.textContent=d.user.firstName+" "+d.user.lastName;return true}catch(e){location.replace("login.html");return false}}

const platformPresets=[
 {name:"YouTube",slug:"youtube",color1:"#FF0000",color2:"#CC0000",icon:"▶",type:"social"},
 {name:"Facebook",slug:"facebook",color1:"#1877F2",color2:"#0D5FC4",icon:"f",type:"social"},
 {name:"Instagram",slug:"instagram",color1:"#833AB4",color2:"#E1306C",icon:"◎",type:"social"},
 {name:"X",slug:"x",color1:"#000000",color2:"#343434",icon:"X",type:"social"},
 {name:"TikTok",slug:"tiktok",color1:"#000000",color2:"#25F4EE",icon:"♪",type:"social"},
 {name:"TikTok Ads",slug:"tiktok",color1:"#000000",color2:"#FE2C55",icon:"Ad",type:"social"},
 {name:"Snapchat",slug:"snapchat",color1:"#FFFC00",color2:"#F4D000",icon:"◉",type:"social"},
 {name:"Reddit",slug:"reddit",color1:"#FF4500",color2:"#D93A00",icon:"●",type:"social"},
 {name:"Discord",slug:"discord",color1:"#5865F2",color2:"#404EED",icon:"◈",type:"social"},
 {name:"WhatsApp",slug:"whatsapp",color1:"#25D366",color2:"#128C7E",icon:"◔",type:"social"},
 {name:"Telegram",slug:"telegram",color1:"#26A5E4",color2:"#168AC0",icon:"➤",type:"social"},
 {name:"LinkedIn",slug:"",color1:"#0A66C2",color2:"#004182",icon:"in",type:"social"},
 {name:"Pinterest",slug:"pinterest",color1:"#BD081C",color2:"#8C0615",icon:"P",type:"social"},
 {name:"Quora",slug:"quora",color1:"#B92B27",color2:"#8E211E",icon:"Q",type:"social"},
 {name:"GitHub",slug:"github",color1:"#181717",color2:"#444444",icon:"⌘",type:"social"},
 {name:"Spotify",slug:"spotify",color1:"#1ED760",color2:"#169C46",icon:"≋",type:"social"},
 {name:"Taimi",slug:"",color1:"#FF477E",color2:"#8D4AE8",icon:"♥",type:"social"},
 {name:"Grindr",slug:"",color1:"#FECB16",color2:"#E5A900",icon:"♜",type:"social"},
 {name:"Bumble",slug:"",color1:"#FFC629",color2:"#E6A800",icon:"⬡",type:"social"},
 {name:"MeetMe",slug:"",color1:"#16A8E2",color2:"#087FC4",icon:"♟",type:"social"},
 {name:"Badoo",slug:"badoo",color1:"#783BF9",color2:"#FF5A8B",icon:"B",type:"social"},
 {name:"Dating Apps",slug:"",color1:"#E83E8C",color2:"#9B51E0",icon:"♥",type:"social"},
 {name:"Private Internet Access",slug:"privateinternetaccess",color1:"#1E811F",color2:"#125B16",icon:"PIA",type:"vpn"},
 {name:"ExpressVPN",slug:"expressvpn",color1:"#DA3940",color2:"#A51F2B",icon:"E",type:"vpn"},
 {name:"Proton VPN",slug:"protonvpn",color1:"#6D4AFF",color2:"#372580",icon:"P",type:"vpn"},
 {name:"VPN",slug:"protonvpn",color1:"#6D4AFF",color2:"#372580",icon:"✓",type:"vpn"}
];
function presetKey(value){const key=String(value||"").trim().toLowerCase();return ["twitter","twitter / x","x.com"].includes(key)?"x":key}
function presetIcon(p){return p.slug?`<img loading="lazy" decoding="async" src="https://cdn.simpleicons.org/${p.slug}/${p.color1.slice(1)}" alt="">`:`<span style="color:${p.color1}">${esc(p.icon)}</span>`}
function renderPlatformPicker(){platformPicker.innerHTML=platformPresets.map(p=>`<button type="button" class="admin-platform-option" data-platform-choice="${esc(p.name)}">${presetIcon(p)}<b>${esc(p.name)}</b><small>${p.type==="vpn"?"VPN":"Social"}</small></button>`).join("")}
function selectPlatform(name){const p=platformPresets.find(x=>presetKey(x.name)===presetKey(name));if(!p)return;p_platform.value=p.name;p_type.value=p.type;p_icon.value=p.icon;p_c1.value=p.color1;p_c2.value=p.color2;brandColorText.textContent=`${p.color1} · ${p.color2}`;document.querySelectorAll("[data-platform-choice]").forEach(b=>b.classList.toggle("selected",presetKey(b.dataset.platformChoice)===presetKey(p.name)))}
renderPlatformPicker();platformPicker.onclick=e=>{const b=e.target.closest("[data-platform-choice]");if(b)selectPlatform(b.dataset.platformChoice)};
document.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-section]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".admin-section").forEach(s=>s.classList.remove("active"));document.getElementById(b.dataset.section).classList.add("active");adminTitle.textContent=b.textContent.trim();adminSidebar.classList.remove("open");if(b.dataset.section==="overview")loadOverviewInsights();if(b.dataset.section==="inventory")loadInventoryOverview();if(b.dataset.section==="sales-reports")renderSalesReports();if(b.dataset.section==="refund-centre")loadRefundCentre();if(b.dataset.section==="security-centre")loadSecurityCentre();if(b.dataset.section==="support")loadSupportTickets();if(b.dataset.section==="audit")loadAuditLog()});adminMenuBtn.onclick=()=>adminSidebar.classList.toggle("open");logoutButton.onclick=()=>{localStorage.removeItem("wayneToken");localStorage.removeItem("wayneUser");location.href="login.html"}
function goAdminSection(section){const button=document.querySelector(`[data-section="${section}"]`);if(button)button.click()}
document.addEventListener("click",e=>{const action=e.target.closest("[data-overview-go]");if(action){goAdminSection(action.dataset.overviewGo);return}const idea=e.target.closest("[data-roadmap]");if(idea){const text=`${idea.dataset.roadmap} is a planned upgrade. It is not active yet, so it cannot change your store.`;window.waynePopup?.(text,"success")||alert(text)}});
async function loadOverviewInsights(){[overviewPendingPayments,overviewLowStock,overviewOpenSupport,overviewPendingOrders].forEach(el=>{if(el)el.textContent="…"});const results=await Promise.allSettled([api("/api/wallet/admin/transactions"),api("/api/products/admin/inventory/overview"),api("/api/support/admin/all"),api("/api/orders/admin/all")]);const value=(index,fallback={})=>results[index].status==="fulfilled"?results[index].value:fallback;const walletRows=value(0,{transactions:[]}).transactions||[];const inventory=value(1,{totals:{}});const tickets=value(2,{tickets:[]}).tickets||[];const overviewOrders=value(3,{orders:[]}).orders||[];if(overviewPendingPayments)overviewPendingPayments.textContent=walletRows.filter(t=>t.provider==="manual_bank"&&t.status==="submitted").length;if(overviewLowStock)overviewLowStock.textContent=Number(inventory.totals?.lowStock||0);if(overviewOpenSupport)overviewOpenSupport.textContent=tickets.filter(t=>t.status!=="resolved").length;if(overviewPendingOrders)overviewPendingOrders.textContent=overviewOrders.filter(o=>["pending","processing"].includes(o.status)).length}
if(refreshOverview)refreshOverview.onclick=()=>loadOverviewInsights().then(()=>show("Overview refreshed successfully.","success"));
function stats(){statProducts.textContent=products.length;statOrders.textContent=orders.length;const paid=orders.filter(o=>o.paymentStatus==="paid");statPaid.textContent=paid.length;statRevenue.textContent=money(paid.reduce((s,o)=>s+Number(o.totalAmount||0),0));if(document.getElementById("sales-reports")?.classList.contains("active"))renderSalesReports()}
function reportOrdersInRange(){if(reportDateRange==="all"&&!reportCustomDates)return [...orders];let start,end;if(reportCustomDates){start=new Date(reportCustomDates.from+"T00:00:00");end=new Date(reportCustomDates.to+"T23:59:59.999")}else{end=new Date();start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-Number(reportDateRange)+1)}return orders.filter(order=>{const date=new Date(order.createdAt);return date>=start&&date<=end})}
function reportRanking(rows,key){const totals={};rows.forEach(order=>{const label=String(order[key]||"Other").trim()||"Other";totals[label]??={count:0,revenue:0};totals[label].count+=Number(order.quantity||1);totals[label].revenue+=Number(order.totalAmount||0)});return Object.entries(totals).sort((a,b)=>b[1].revenue-a[1].revenue)}
function renderRanking(element,rows){if(!rows.length){element.innerHTML='<div class="empty">No paid sales in this period.</div>';return}const max=Math.max(...rows.map(([,value])=>value.revenue),1);element.innerHTML=rows.slice(0,6).map(([label,value],index)=>`<div class="report-rank-row"><span class="report-rank-number">${index+1}</span><div><strong>${esc(label)}</strong><small>${value.count} sold · ${money(value.revenue)}</small><i style="width:${Math.max(5,value.revenue/max*100)}%"></i></div></div>`).join("")}
function renderSalesReports(){if(!reportRevenue)return;const rows=reportOrdersInRange(),paid=rows.filter(order=>order.paymentStatus==="paid"),revenue=paid.reduce((sum,order)=>sum+Number(order.totalAmount||0),0);reportRevenue.textContent=money(revenue);reportPaid.textContent=paid.length;reportOrders.textContent=rows.length;reportAverage.textContent=money(paid.length?revenue/paid.length:0);reportPaidRate.textContent=`${rows.length?Math.round(paid.length/rows.length*100):0}% payment rate`;reportPeriodLabel.textContent=reportCustomDates?`${new Date(reportCustomDates.from+"T00:00:00").toLocaleDateString()} – ${new Date(reportCustomDates.to+"T00:00:00").toLocaleDateString()}`:reportDateRange==="all"?"All recorded sales":`Last ${reportDateRange} days`;const daily={};paid.forEach(order=>{const key=new Date(order.createdAt).toISOString().slice(0,10);daily[key]=(daily[key]||0)+Number(order.totalAmount||0)});const days=Object.entries(daily).sort((a,b)=>a[0].localeCompare(b[0])),max=Math.max(...days.map(([,amount])=>amount),1);revenueChart.innerHTML=days.length?days.map(([date,amount])=>`<div class="revenue-bar-item" title="${date}: ${money(amount)}"><strong>${money(amount)}</strong><div><i style="height:${Math.max(8,amount/max*100)}%"></i></div><small>${new Date(date+"T00:00:00").toLocaleDateString("en-NG",{day:"numeric",month:"short"})}</small></div>`).join(""):'<div class="empty">No paid sales to chart in this period.</div>';const statusNames=["completed","processing","pending","cancelled","refunded"];reportStatuses.innerHTML=statusNames.map(status=>{const count=rows.filter(order=>order.status===status).length,percent=rows.length?Math.round(count/rows.length*100):0;return `<div class="report-status-row"><span><i class="${status}"></i>${status}</span><b>${count}</b><div><i style="width:${percent}%"></i></div><small>${percent}%</small></div>`}).join("");renderRanking(reportProducts,reportRanking(paid,"productName"));renderRanking(reportPlatforms,reportRanking(paid,"platform"));reportSalesTable.innerHTML=paid.length?paid.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,20).map(order=>`<tr><td>${new Date(order.createdAt).toLocaleString()}</td><td>${esc(order.user?.email||"Customer")}</td><td>${esc(order.productName)}</td><td>${esc(order.platform||"—")}</td><td>${money(order.totalAmount)}</td><td><span class="report-paid-chip">Paid</span></td></tr>`).join(""):'<tr><td colspan="6">No paid sales in this period.</td></tr>'}
document.querySelectorAll("[data-report-range]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-report-range]").forEach(item=>item.classList.remove("active"));button.classList.add("active");reportDateRange=button.dataset.reportRange;reportCustomDates=null;reportFrom.value="";reportTo.value="";renderSalesReports()});applyReportDates.onclick=()=>{if(!reportFrom.value||!reportTo.value)return show("Choose both From and To dates.");if(reportFrom.value>reportTo.value)return show("The From date cannot be later than the To date.");reportCustomDates={from:reportFrom.value,to:reportTo.value};document.querySelectorAll("[data-report-range]").forEach(item=>item.classList.remove("active"));renderSalesReports();show("Sales report dates applied.","success")};exportSalesCsv.onclick=()=>{const rows=reportOrdersInRange(),safe=value=>{let text=String(value??"");if(/^[=+\-@]/.test(text))text="'"+text;return `"${text.replaceAll('"','""')}"`},csv=[["Date","Order ID","Customer","Product","Platform","Quantity","Amount","Payment","Order Status"],...rows.map(order=>[new Date(order.createdAt).toISOString(),order._id,order.user?.email||"",order.productName,order.platform||"",order.quantity||1,order.totalAmount,order.paymentStatus,order.status])].map(row=>row.map(safe).join(",")).join("\r\n"),blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`wayne-logs-sales-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);show("Sales report downloaded successfully.","success")};
function eligibleRefundOrders(){const query=refundSearch.value.trim().toLowerCase();return orders.filter(order=>order.paymentStatus==="paid"&&order.paymentMethod==="wallet"&&(!query||[order._id,order.productName,order.platform,order.user?.email,order.user?.firstName,order.user?.lastName].some(value=>String(value||"").toLowerCase().includes(query))))}
function renderRefundOrders(){const eligible=eligibleRefundOrders();refundEligibleCount.textContent=`${eligible.length} eligible`;refundOrderList.innerHTML=eligible.length?eligible.map(order=>`<button type="button" class="refund-order-card ${String(order._id)===String(selectedRefundOrder)?"selected":""}" data-refund-order="${esc(order._id)}"><span><strong>${esc(order.productName)}</strong><small>${esc(order.user?.email||"Customer")} · ${new Date(order.createdAt).toLocaleString()}<br>Order ${esc(order._id)}</small></span><b>${money(order.totalAmount)}</b></button>`).join(""):'<div class="empty">No eligible paid wallet orders found.</div>'}
function selectRefundOrder(id){const order=orders.find(item=>String(item._id)===String(id)&&item.paymentStatus==="paid"&&item.paymentMethod==="wallet");if(!order)return;selectedRefundOrder=order._id;refundOrderTitle.textContent=order.productName;refundOrderMeta.textContent=`${order.user?.email||"Customer"} · Order ${order._id}`;refundOrderAmount.textContent=money(order.totalAmount);refundForm.reset();refundConfirmPanel.hidden=false;renderRefundOrders();refundConfirmPanel.scrollIntoView({behavior:"smooth",block:"center"})}
async function loadRefundCentre(){try{const [orderData,walletData]=await Promise.all([api("/api/orders/admin/all"),api("/api/wallet/admin/transactions")]);orders=orderData.orders||[];refundTransactions=(walletData.transactions||[]).filter(transaction=>transaction.provider==="order_refund"&&transaction.status==="completed");renderRefundOrders();refundHistoryTable.innerHTML=refundTransactions.length?refundTransactions.map(transaction=>`<tr><td>${new Date(transaction.createdAt).toLocaleString()}</td><td>${esc(transaction.user?.email||"Customer")}</td><td>${esc(transaction.order?.productName||transaction.order?._id||"—")}</td><td>${money(transaction.amountKobo/100)}</td><td>${esc(transaction.reviewNote||transaction.description||"—")}</td></tr>`).join(""):'<tr><td colspan="5">No completed refunds.</td></tr>';stats()}catch(error){show(error.message)}}
refundOrderList.onclick=e=>{const card=e.target.closest("[data-refund-order]");if(card)selectRefundOrder(card.dataset.refundOrder)};refundSearch.oninput=renderRefundOrders;refreshRefunds.onclick=()=>loadRefundCentre().then(()=>show("Refund Centre refreshed.","success"));refundForm.onsubmit=async e=>{e.preventDefault();const order=orders.find(item=>String(item._id)===String(selectedRefundOrder));if(!order)return show("Select an eligible order first.");if(!refundAcknowledgement.checked)return show("Confirm that you understand the refund action.");refundSubmitButton.disabled=true;refundSubmitButton.textContent="Refunding securely…";try{await api(`/api/orders/admin/${encodeURIComponent(order._id)}/refund`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:refundReason.value,adminPassword:refundAdminPassword.value})});selectedRefundOrder="";refundConfirmPanel.hidden=true;await Promise.all([loadRefundCentre(),loadUsers(),loadAuditLog()]);show("Refund successful. The full amount was returned to the customer's wallet.","success")}catch(error){refundAdminPassword.value="";show(error.message)}finally{refundSubmitButton.disabled=false;refundSubmitButton.textContent="Refund Full Amount Securely"}};
async function loadSecurityCentre(){try{securityScore.textContent="Checking…";const data=await api("/api/security/admin/overview"),metrics=data.metrics||{},protections=data.protections||[],events=data.events||[];securityFailedPayments.textContent=metrics.failedPayments||0;securityCancelledOrders.textContent=metrics.cancelledOrders||0;securityRefundsToday.textContent=metrics.refundsToday||0;securityAdminCredits.textContent=metrics.adminCredits||0;const active=protections.filter(item=>item.active).length;securityScore.textContent=`${active}/${protections.length} active`;securityScore.className="security-score active";securityProtectionList.innerHTML=protections.map(item=>`<article class="security-protection ${item.active?"active":"warning"}"><span>${item.active?"✓":"!"}</span><div><strong>${esc(item.name)}</strong><small>${esc(item.detail)}</small></div><b>${item.active?"ACTIVE":"CHECK"}</b></article>`).join("");securityEventTable.innerHTML=events.length?events.map(event=>`<tr><td>${new Date(event.date).toLocaleString()}</td><td>${esc(String(event.type||"activity").replaceAll("_"," "))}</td><td>${esc(event.email||"—")}</td><td>${esc(event.detail||"—")}</td><td>${event.amountKobo?money(event.amountKobo/100):"—"}</td><td><span class="security-event-status ${esc(event.status)}">${esc(event.status)}</span></td></tr>`).join(""):'<tr><td colspan="6">No sensitive activity recorded yet.</td></tr>'}catch(error){securityScore.textContent="Check failed";securityScore.className="security-score warning";show(error.message)}}
refreshSecurity.onclick=()=>loadSecurityCentre().then(()=>show("Security check completed.","success"));
function normalizeInventoryRecord(value){return String(value||"").replace(/\s*\r?\n\s*/g," ").replace(/\s+/g," ").trim()}
function syncGuidedInventory(){const records=[...guidedInventoryList.querySelectorAll("[data-guided-record]")].map(input=>normalizeInventoryRecord(input.value)).filter(Boolean),unique=[...new Set(records)];p_inventory.value=unique.join("\n");guidedInventoryCount.textContent=`${unique.length} ready`;[...guidedInventoryList.children].forEach((card,index)=>{card.querySelector(".guided-record-number").textContent=`Record ${index+1}`})}
function addGuidedInventoryRecord(focus=true){const number=guidedInventoryList.children.length+1,card=document.createElement("div");card.className="guided-record-card";card.innerHTML=`<div class="guided-record-top"><strong class="guided-record-number">Record ${number}</strong><button type="button" class="guided-remove-record" aria-label="Remove record">×</button></div><textarea data-guided-record rows="3" placeholder="Paste one complete delivery code or instruction here"></textarea><button type="button" class="guided-next-record">Save & Next →</button>`;guidedInventoryList.appendChild(card);if(focus)card.querySelector("textarea").focus();syncGuidedInventory()}
function resetGuidedInventory(){guidedInventoryList.innerHTML="";p_inventory.value="";addGuidedInventoryRecord(false)}
guidedInventoryList.addEventListener("input",syncGuidedInventory);guidedInventoryList.addEventListener("click",e=>{const next=e.target.closest(".guided-next-record"),remove=e.target.closest(".guided-remove-record");if(next){const input=next.parentElement.querySelector("textarea");input.value=normalizeInventoryRecord(input.value);if(!input.value){show("Paste an inventory item before moving to the next record.");input.focus();return}syncGuidedInventory();const following=next.parentElement.nextElementSibling;if(following)following.querySelector("textarea").focus();else addGuidedInventoryRecord(true)}if(remove){const card=remove.closest(".guided-record-card");if(guidedInventoryList.children.length===1)card.querySelector("textarea").value="";else card.remove();syncGuidedInventory()}});addInventoryRecord.onclick=()=>addGuidedInventoryRecord(true);resetGuidedInventory();
async function loadProducts(){const d=await api("/api/products/admin/all");products=d.products||[];adminProductTable.innerHTML=products.length?products.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.platform)}</small></td><td>${esc(p.type)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${esc(p.status)}</td><td><button class="ghost-btn" onclick="editProduct('${p._id}')">Edit</button> <button class="danger-btn" onclick="deleteProduct('${p._id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="6">No products.</td></tr>`;stats()}
async function loadOrders(){const d=await api("/api/orders/admin/all");orders=d.orders||[];adminOrderTable.innerHTML=orders.length?orders.map(o=>`<tr><td>${esc(o._id)}</td><td>${esc((o.user?.firstName||"")+" "+(o.user?.lastName||""))}<br><small>${esc(o.user?.email||"")}</small></td><td>${esc(o.productName)}</td><td>${money(o.totalAmount)}</td><td>${esc(o.paymentStatus)}</td><td><select class="filter-select" onchange="setOrderStatus('${o._id}',this.value)">${["pending","processing","completed","cancelled","refunded"].map(s=>`<option value="${s}" ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join(""):`<tr><td colspan="6">No orders.</td></tr>`;stats()}
async function loadUsers(){const d=await api("/api/auth/admin/users");users=d.users||[];const money=k=>"₦"+(Number(k||0)/100).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});adminUserTable.innerHTML=users.length?users.map(u=>`<tr><td>${esc(u.firstName+" "+u.lastName)}</td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${money(u.walletBalanceKobo)}</td><td>${esc(u.role)}</td><td>${u.isActive?"Active":"Disabled"}</td><td>${u.role==="user"?`<button class="danger-btn" type="button" onclick="prepareClear('${encodeURIComponent(u.email)}')">Clear Balance</button>`:"—"}</td></tr>`).join(""):`<tr><td colspan="7">No users.</td></tr>`}
async function loadSiteSettings(){const d=await api("/api/settings/admin"),s=d.settings||{};announcementEnabled.checked=!!s.announcementEnabled;announcementTitle.value=s.announcementTitle||"";announcementMessage.value=s.announcementMessage||"";telegramUrl.value=s.telegramUrl||""}
async function loadAuditLog(){try{adminAuditTable.innerHTML='<tr><td colspan="6">Loading secure audit records…</td></tr>';const q=new URLSearchParams();if(auditSearch.value.trim())q.set("search",auditSearch.value.trim());if(auditEntity.value)q.set("entity",auditEntity.value);const d=await api("/api/audit?"+q.toString()),rows=d.logs||[];adminAuditTable.innerHTML=rows.length?rows.map(log=>`<tr><td>${new Date(log.createdAt).toLocaleString()}</td><td><strong>${esc((log.admin?.firstName||"")+" "+(log.admin?.lastName||""))}</strong><br><small>${esc(log.admin?.email||"")}</small></td><td><span class="audit-action">${esc(log.action.replaceAll("."," "))}</span><br><small>${esc(log.entity)}</small></td><td>${esc(log.target||"—")}</td><td>${esc(log.summary)}${log.metadata?.reason?`<br><small>Reason: ${esc(log.metadata.reason)}</small>`:""}</td><td>${esc(log.ipAddress||"—")}</td></tr>`).join(""):'<tr><td colspan="6">No matching audit records.</td></tr>'}catch(e){adminAuditTable.innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`}}
searchAudit.onclick=loadAuditLog;refreshAudit.onclick=()=>{auditSearch.value="";auditEntity.value="";loadAuditLog()};auditSearch.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();loadAuditLog()}};
passwordSearchForm.onsubmit=async e=>{e.preventDefault();passwordSearchButton.disabled=true;temporaryPasswordResult.hidden=true;temporaryPasswordValue.textContent="";try{const email=passwordHelpEmail.value.trim().toLowerCase(),d=await api(`/api/auth/admin/password-assistance/search?email=${encodeURIComponent(email)}`),u=d.customer;passwordHelpCustomerEmail=u.email;passwordCustomerName.textContent=`${u.firstName} ${u.lastName}`;passwordCustomerMeta.textContent=`${u.email} · ${u.phone} · ${u.isActive?"Active":"Disabled"}${u.mustChangePassword?" · Temporary password pending":""}`;passwordCustomerResult.hidden=false;passwordHelpAdminPassword.value="";show("Customer found. Confirm your admin password to continue.","success")}catch(error){passwordCustomerResult.hidden=true;passwordHelpCustomerEmail="";show(error.message)}finally{passwordSearchButton.disabled=false}};
temporaryPasswordForm.onsubmit=async e=>{e.preventDefault();if(!passwordHelpCustomerEmail)return;const warning="Generate a new one-use temporary password? This will immediately log the customer out from every device and replace their current password.";temporaryPasswordButton.disabled=true;temporaryPasswordButton.textContent="Generating securely…";try{const d=await api("/api/auth/admin/password-assistance/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:passwordHelpCustomerEmail,adminPassword:passwordHelpAdminPassword.value})});passwordHelpAdminPassword.value="";temporaryPasswordValue.textContent=d.temporaryPassword;temporaryPasswordResult.hidden=false;temporaryPasswordResult.scrollIntoView({behavior:"smooth",block:"center"});show("One-use temporary password created successfully.","success")}catch(error){passwordHelpAdminPassword.value="";show(error.message)}finally{temporaryPasswordButton.disabled=false;temporaryPasswordButton.textContent="Generate One-Use Password"}};
copyTemporaryPassword.onclick=async()=>{const value=temporaryPasswordValue.textContent;if(!value)return;try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement("textarea");area.value=value;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove()}copyTemporaryPassword.textContent="Copied!";window.waynePopup?.("Temporary password copied. Send it only to the verified customer.","success");setTimeout(()=>copyTemporaryPassword.textContent="Copy Temporary Password",1800)};
async function loadInventoryOverview(){try{const d=await api("/api/products/admin/inventory/overview");inventoryRows=d.inventory||[];inventoryAvailable.textContent=d.totals?.available||0;inventorySold.textContent=d.totals?.sold||0;inventoryLow.textContent=d.totals?.lowStock||0;inventoryProducts.innerHTML=inventoryRows.length?inventoryRows.map(p=>`<button type="button" class="inventory-product-card ${p.lowStock?"low":""} ${String(selectedInventoryProduct)===String(p.id)?"selected":""}" data-inventory-product="${esc(p.id)}" aria-label="Add inventory to ${esc(p.name)}"><span><strong>${esc(p.name)}</strong><small>${esc(p.platform)} · ${esc(p.status)}</small></span><span class="inventory-card-count"><b>${p.available}</b> available<small>${p.sold} sold</small></span><span class="inventory-card-action">Add Inventory →</span>${p.lowStock?'<em>Low stock</em>':""}</button>`).join(""):'<div class="empty">No inventory-managed products yet.</div>';if(selectedInventoryProduct&&inventoryRows.some(p=>String(p.id)===String(selectedInventoryProduct)))await loadInventoryDetail(selectedInventoryProduct,false)}catch(e){show(e.message)}}
async function loadInventoryDetail(id,scroll=true){try{selectedInventoryProduct=id;show("Opening the selected product inventory…","success");const d=await api(`/api/products/admin/inventory/${encodeURIComponent(id)}`),p=d.product,items=d.items||[];inventoryManager.hidden=false;inventoryProductName.textContent=p.name;inventoryProductMeta.textContent=`${p.platform} · ${p.status}`;inventoryProductCount.textContent=`${p.stock} available`;inventoryHistory.innerHTML=items.length?items.map(i=>`<tr><td>${new Date(i.createdAt).toLocaleString()}</td><td><span class="inventory-status ${esc(i.status)}">${esc(i.status)}</span></td><td>${i.soldTo?`${esc((i.soldTo.firstName||"")+" "+(i.soldTo.lastName||""))}<br><small>${esc(i.soldTo.email||"")}</small>`:"—"}</td><td>${i.soldAt?new Date(i.soldAt).toLocaleString():"—"}</td><td>${i.order?esc(i.order):"—"}</td></tr>`).join(""):'<tr><td colspan="5">No inventory records.</td></tr>';document.querySelectorAll("[data-inventory-product]").forEach(b=>b.classList.toggle("selected",String(b.dataset.inventoryProduct)===String(id)));if(scroll)setTimeout(()=>inventoryManager.scrollIntoView({behavior:"smooth",block:"start"}),80)}catch(e){show(e.message)}}
inventoryProducts.onclick=async e=>{const b=e.target.closest("[data-inventory-product]");if(!b)return;e.preventDefault();await loadInventoryDetail(b.dataset.inventoryProduct,true)};
refreshInventory.onclick=loadInventoryOverview;
restockForm.onsubmit=async e=>{e.preventDefault();if(!selectedInventoryProduct)return;const inventoryItems=restockLines.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!inventoryItems.length)return;restockButton.disabled=true;restockButton.textContent="Adding securely…";try{const d=await api(`/api/products/admin/inventory/${encodeURIComponent(selectedInventoryProduct)}/restock`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryItems})});restockForm.reset();show(`${d.added} new records added. ${d.duplicates} duplicates ignored.`,"success");await loadProducts();await loadInventoryOverview()}catch(e){show(e.message)}finally{restockButton.disabled=false;restockButton.textContent="Add Inventory Securely"}};
async function loadSupportTickets(){try{const d=await api("/api/support/admin/all");supportTickets=d.tickets||[];supportOpen.textContent=supportTickets.filter(t=>t.status==="open").length;supportProgress.textContent=supportTickets.filter(t=>t.status==="in_progress").length;supportResolved.textContent=supportTickets.filter(t=>t.status==="resolved").length;adminTicketList.innerHTML=supportTickets.length?supportTickets.map(t=>`<button type="button" class="support-ticket ${String(t._id)===String(selectedSupportTicket)?"selected":""}" data-admin-ticket="${esc(t._id)}"><span><strong>${esc(t.subject)}</strong><small>${esc((t.user?.firstName||"")+" "+(t.user?.lastName||""))} · ${esc(t.user?.email||"")}<br>${t.order?esc(t.order.productName):"General support"} · ${new Date(t.lastReplyAt).toLocaleString()}</small></span><span class="support-status ${esc(t.status)}">${esc(t.status.replace("_"," "))}</span></button>`).join(""):'<div class="empty">No customer support tickets.</div>';if(selectedSupportTicket){const t=supportTickets.find(x=>String(x._id)===String(selectedSupportTicket));if(t)renderAdminConversation(t)}}catch(e){show(e.message)}}
function renderAdminConversation(t){selectedSupportTicket=t._id;adminConversation.hidden=false;adminConversationTitle.textContent=t.subject;adminConversationMeta.textContent=`${t.user?.firstName||""} ${t.user?.lastName||""} · ${t.user?.email||""}${t.order?" · Order: "+t.order._id:""}`;adminTicketStatus.value=t.status;const messages=[{role:"customer",message:t.message,createdAt:t.createdAt},...(t.replies||[])];adminConversationMessages.innerHTML=messages.map(m=>`<article class="support-message ${esc(m.role)}"><strong>${m.role==="admin"?"You (Admin)":esc(t.user?.firstName||"Customer")}</strong><p>${esc(m.message)}</p><small>${new Date(m.createdAt).toLocaleString()}</small></article>`).join("");document.querySelectorAll("[data-admin-ticket]").forEach(b=>b.classList.toggle("selected",String(b.dataset.adminTicket)===String(t._id)))}
adminTicketList.onclick=e=>{const b=e.target.closest("[data-admin-ticket]");if(!b)return;const t=supportTickets.find(x=>String(x._id)===String(b.dataset.adminTicket));if(t)renderAdminConversation(t)};refreshSupport.onclick=loadSupportTickets;adminTicketStatus.onchange=async()=>{if(!selectedSupportTicket)return;try{await api(`/api/support/admin/${encodeURIComponent(selectedSupportTicket)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:adminTicketStatus.value})});await loadSupportTickets()}catch(e){show(e.message)}};adminReplyForm.onsubmit=async e=>{e.preventDefault();if(!selectedSupportTicket)return;adminReplyButton.disabled=true;try{await api(`/api/support/admin/${encodeURIComponent(selectedSupportTicket)}/replies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:adminReplyMessage.value,resolve:resolveWithReply.checked})});adminReplyForm.reset();show("Support reply sent.","success");await loadSupportTickets()}catch(e){show(e.message)}finally{adminReplyButton.disabled=false}};
window.setOrderStatus=async(id,status)=>{try{await api(`/api/orders/admin/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await loadOrders()}catch(e){show(e.message)}}
function clearForm(){editingProductId="";productForm.dataset.mode="create";productForm.reset();resetGuidedInventory();p_id.value="";p_platform.value="";p_icon.value="";p_stock.value="0";p_c1.value="#1556c9";p_c2.value="#09a2df";p_delivery.value="instant";brandColorText.textContent="Select a platform";document.querySelectorAll("[data-platform-choice]").forEach(b=>b.classList.remove("selected"));productFormTitle.textContent="Add Product";clearProduct.textContent="Clear"}clearProduct.onclick=clearForm
window.editProduct=id=>{const p=products.find(x=>String(x._id)===String(id));if(!p)return show("That product could not be opened for editing.");editingProductId=String(p._id);productForm.dataset.mode="edit";p_id.value=editingProductId;p_name.value=p.name;selectPlatform(p.platform);if(!platformPresets.some(x=>presetKey(x.name)===presetKey(p.platform))){p_platform.value=p.platform;p_type.value=p.type;p_icon.value=p.icon||"";p_c1.value=p.color1||"#1556c9";p_c2.value=p.color2||"#09a2df";brandColorText.textContent=`${p_c1.value} · ${p_c2.value}`}p_price.value=p.price;p_stock.value=p.stock;p_delivery.value="instant";p_status.value=p.status;p_description.value=p.description||"";resetGuidedInventory();productFormTitle.textContent=`Editing: ${p.name} — changes will replace this product`;clearProduct.textContent="Cancel Editing";document.getElementById("products").scrollIntoView({behavior:"smooth",block:"start"});show(`Editing “${p.name}”. Saving will update this product, not create another one.`,"success")}
window.deleteProduct=async id=>{try{await api("/api/products/"+id,{method:"DELETE"});await loadProducts()}catch(e){show(e.message)}}
productForm.onsubmit=async e=>{e.preventDefault();if(productSaveBusy)return;const id=editingProductId||p_id.value;if(!p_platform.value){show("Choose a platform from the grid first.");platformPicker.scrollIntoView({behavior:"smooth",block:"center"});return}const inventoryItems=p_inventory.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!id&&!inventoryItems.length){show("Paste at least one unique delivery record, one per line.");p_inventory.focus();return}const body={name:p_name.value.trim(),platform:p_platform.value.trim(),type:p_type.value,price:Number(p_price.value),icon:p_icon.value.trim(),color1:p_c1.value,color2:p_c2.value,deliveryType:"instant",inventoryManaged:true,inventoryItems,status:p_status.value,description:p_description.value.trim(),privateDelivery:""},submit=e.submitter||productForm.querySelector('button[type="submit"],button:not([type])');productSaveBusy=true;if(submit){submit.dataset.wayneBusy="1";submit.disabled=true;submit.textContent=id?"Updating Product…":"Creating Product…"}try{const result=await api(id?"/api/products/"+encodeURIComponent(id):"/api/products",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(id&&String(result.product?._id)!==String(id))throw new Error("The server did not update the selected product. Nothing else was created.");const action=id?"updated":"created";clearForm();await Promise.all([loadProducts(),loadInventoryOverview()]);show(`Product ${action} successfully. ${inventoryItems.length?inventoryItems.length+" inventory lines processed.":"Existing inventory preserved."}`,"success")}catch(error){show(error.message)}finally{productSaveBusy=false;if(submit){delete submit.dataset.wayneBusy;submit.disabled=false;submit.textContent="Save Product & Inventory"}}}
siteSettingsForm.onsubmit=async e=>{e.preventDefault();try{await api("/api/settings/admin",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({announcementEnabled:announcementEnabled.checked,announcementTitle:announcementTitle.value,announcementMessage:announcementMessage.value,telegramUrl:telegramUrl.value})});show("Announcement and Telegram settings saved.","success")}catch(e){show(e.message)}};
const broadcastForm=$("broadcastForm"),broadcastTitle=$("broadcastTitle"),broadcastMessage=$("broadcastMessage"),broadcastLink=$("broadcastLink"),broadcastButton=$("broadcastButton");broadcastForm.onsubmit=async e=>{e.preventDefault();broadcastButton.disabled=true;try{const d=await api("/api/notifications/admin/broadcast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:broadcastTitle.value,message:broadcastMessage.value,link:broadcastLink.value})});broadcastForm.reset();broadcastLink.value="index.html";show(`Notification published to ${d.recipients} customers.`,"success")}catch(e){show(e.message)}finally{broadcastButton.disabled=false}};
refreshOrders.onclick=loadOrders;apiUrlInput.value=API_URL;saveApiUrl.onclick=()=>{localStorage.setItem("wayneApiUrl",apiUrlInput.value.replace(/\/$/,""));location.reload()};(async()=>{if(!(await checkAdmin()))return;try{await Promise.all([loadProducts(),loadOrders(),loadUsers(),loadSiteSettings()]);await loadOverviewInsights()}catch(e){show(e.message)}})();
