const API_URL=localStorage.getItem("wayneApiUrl")||window.WAYNE_API_URL||"http://localhost:5000";
const token=localStorage.getItem("wayneToken");
const $=id=>document.getElementById(id);
const accountLink=$("accountLink"),adminLink=$("adminLink"),searchInput=$("searchInput"),filterSelect=$("filterSelect"),productGrid=$("productGrid"),cartItems=$("cartItems"),cartTotal=$("cartTotal"),checkoutBtn=$("checkoutBtn"),cartButton=$("cartButton"),cartDrawer=$("cartDrawer"),overlay=$("overlay"),modalPlatform=$("modalPlatform"),modalTitle=$("modalTitle"),modalDesc=$("modalDesc"),modalPrice=$("modalPrice"),modalArt=$("modalArt"),productModal=$("productModal"),checkoutSummary=$("checkoutSummary"),checkoutModal=$("checkoutModal"),checkoutMessage=$("checkoutMessage"),payButton=$("payButton"),modalAdd=$("modalAdd");
let products=[],currentProduct=null,cart=[];
try{cart=JSON.parse(localStorage.getItem("wayneCart")||"[]")}catch(e){cart=[]}
function money(n){return"₦"+Number(n||0).toLocaleString("en-NG")}function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function user(){try{return JSON.parse(localStorage.getItem("wayneUser")||"null")}catch(e){return null}}
function setupAccount(){const u=user();if(u){accountLink.textContent="My Orders";accountLink.href="orders.html";if(u.role==="admin")adminLink.style.display="inline-block"}}
function saveCart(){localStorage.setItem("wayneCart",JSON.stringify(cart));document.querySelectorAll("[data-cart-count]").forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0))}
async function loadProducts(){try{const r=await fetch(API_URL+"/api/products");const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not load products");products=d.products||[];renderProducts();renderCart()}catch(e){productGrid.innerHTML=`<div class="empty" style="grid-column:1/-1">Backend not connected.<br><small>${esc(e.message)}</small></div>`}}
function renderProducts(){const q=(searchInput.value||"").toLowerCase(),f=filterSelect.value;const list=products.filter(p=>(p.name+" "+p.platform+" "+p.description).toLowerCase().includes(q)&&(f==="all"||p.type===f));productGrid.innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-art" style="--c1:${esc(p.color1)};--c2:${esc(p.color2)}">${esc(p.icon||"★")}</div><div class="product-body"><div class="tags"><span class="tag">${esc(p.platform)}</span><span class="tag">${esc(p.type)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-bottom"><div><div class="price">${money(p.price)}</div><div class="stock">${p.stock>0?p.stock+" available":"Out of stock"}</div></div><div class="product-actions"><button class="small-btn" onclick="openProduct('${p._id}')">View</button><button class="small-btn buy" ${p.stock<1?"disabled":""} onclick="addToCart('${p._id}')">Add</button></div></div></div></article>`).join(""):`<div class="empty" style="grid-column:1/-1">No matching products.</div>`}
window.addToCart=id=>{const p=products.find(x=>x._id===id);if(!p||p.stock<1)return;const i=cart.find(x=>x.id===id);if(i)i.qty=Math.min(i.qty+1,p.stock);else cart.push({id,qty:1});saveCart();renderCart();openCart()};window.removeFromCart=id=>{cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}
function renderCart(){let total=0;cartItems.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x._id===i.id);if(!p)return"";total+=p.price*i.qty;return`<div class="cart-item"><div class="cart-art">${esc(p.icon||"★")}</div><div class="meta"><strong>${esc(p.name)}</strong><small>${money(p.price)} × ${i.qty}</small></div><button class="icon-btn" onclick="removeFromCart('${p._id}')">×</button></div>`}).join(""):`<div class="empty">Your cart is empty.</div>`;cartTotal.textContent=money(total);checkoutBtn.disabled=!cart.length}
function openCart(){cartDrawer.classList.add("open");overlay.classList.add("show")}window.closeCart=()=>{cartDrawer.classList.remove("open");overlay.classList.remove("show")};
window.openProduct=id=>{currentProduct=products.find(x=>x._id===id);if(!currentProduct)return;modalPlatform.textContent=currentProduct.platform;modalTitle.textContent=currentProduct.name;modalDesc.textContent=currentProduct.description;modalPrice.textContent=money(currentProduct.price);modalArt.textContent=currentProduct.icon||"★";modalArt.style.background=`linear-gradient(135deg,${currentProduct.color1||"#7c5cff"},${currentProduct.color2||"#ff5db1"})`;productModal.classList.add("show")};window.closeProduct=()=>productModal.classList.remove("show")
function openCheckout(){if(!token){location.href="login.html";return}if(cart.length!==1||cart[0].qty!==1){alert("Checkout one product at a time for secure fulfillment.");return}closeCart();const p=products.find(x=>x._id===cart[0].id);checkoutSummary.textContent=p?`${p.name} — ${money(p.price)}`:"";checkoutModal.classList.add("show")}window.closeCheckout=()=>checkoutModal.classList.remove("show")
async function pay(){checkoutMessage.className="message";const item=cart[0];try{let r=await fetch(API_URL+"/api/orders",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({productId:item.id})});let d=await r.json();if(!r.ok)throw new Error(d.message||"Could not create order");r=await fetch(API_URL+`/api/orders/${d.order._id}/paystack/initialize`,{method:"POST",headers:{Authorization:"Bearer "+token}});d=await r.json();if(!r.ok)throw new Error(d.message||"Could not start payment");cart=[];saveCart();location.href=d.authorizationUrl}catch(e){checkoutMessage.textContent=e.message;checkoutMessage.className="message error";checkoutMessage.style.display="block"}}
searchInput.addEventListener("input",renderProducts);filterSelect.addEventListener("change",renderProducts);cartButton.onclick=openCart;overlay.onclick=closeCart;checkoutBtn.onclick=openCheckout;payButton.onclick=pay;modalAdd.onclick=()=>{if(currentProduct){addToCart(currentProduct._id);closeProduct()}};setupAccount();saveCart();loadProducts();
