(function(){
  const walletTable=document.getElementById("adminWalletTable"),refresh=document.getElementById("refreshWallets"),userTable=document.getElementById("adminUserTable"),creditForm=document.getElementById("adminCreditForm"),creditEmail=document.getElementById("creditEmail"),creditAmount=document.getElementById("creditAmount"),creditReason=document.getElementById("creditReason"),creditAdminPassword=document.getElementById("creditAdminPassword"),creditButton=document.getElementById("creditButton"),clearForm=document.getElementById("adminClearForm"),clearEmail=document.getElementById("clearEmail"),clearReason=document.getElementById("clearReason"),clearAdminPassword=document.getElementById("clearAdminPassword"),clearButton=document.getElementById("clearButton");
  const token=localStorage.getItem("wayneToken"),base=localStorage.getItem("wayneApiUrl")||window.WAYNE_API_URL||"http://localhost:5000";
  const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
  const moneyKobo=k=>"₦"+(Number(k||0)/100).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
  async function request(path,options={}){options.headers={...(options.headers||{}),Authorization:"Bearer "+token};const r=await fetch(base+path,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
  async function loadWallets(){
    try{const d=await request("/api/wallet/admin/transactions"),rows=d.transactions||[];walletTable.innerHTML=rows.length?rows.map(t=>{const manual=t.provider==="manual_bank";let controls="";if(manual&&t.status==="submitted")controls=`<div class="review-actions"><button class="primary-btn" onclick="reviewTopup('${t._id}','approve')">✓ Approve</button> <button class="danger-btn" onclick="reviewTopup('${t._id}','reject')">✕ Reject</button></div>`;else if(manual&&t.status==="completed")controls='<div class="review-result approved">✓ Approved</div>';else if(manual&&t.status==="rejected")controls='<div class="review-result rejected">✕ Rejected</div>';else if(manual)controls='<div class="review-result waiting">Waiting for customer submission</div>';return `<tr><td>${new Date(t.createdAt).toLocaleString()}</td><td>${esc((t.user?.firstName||"")+" "+(t.user?.lastName||""))}<br><small>${esc(t.user?.email||"")}</small></td><td>${esc(t.type)}${t.customerReference?`<br><small>Bank ref: ${esc(t.customerReference)}</small>`:""}</td><td>${moneyKobo(t.amountKobo)}</td><td>${esc(t.status)}</td><td>${esc(t.reference)}${controls}</td></tr>`}).join(""):'<tr><td colspan="6">No wallet transactions.</td></tr>'}catch(e){walletTable.innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`}
  }
  window.reviewTopup=async(id,decision)=>{
    const warning=decision==="approve"?"Approve only after you personally confirm the exact payment in your bank account. Credit this wallet now?":"Reject this top-up request?";
    if(!confirm(warning))return;
    try{await request(`/api/wallet/admin/transactions/${encodeURIComponent(id)}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});alert(decision==="approve"?"Payment approved successfully. The customer's wallet has been credited.":"Payment rejected successfully. The customer's wallet was not credited.");await loadWallets();await loadBalances()}catch(e){alert(e.message)}
  };
  async function loadBalances(){
    try{const d=await request("/api/auth/admin/users"),rows=d.users||[];userTable.innerHTML=rows.length?rows.map(u=>`<tr><td>${esc(u.firstName+" "+u.lastName)}</td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${moneyKobo(u.walletBalanceKobo)}</td><td>${esc(u.role)}</td><td>${u.isActive?"Active":"Disabled"}</td><td>${u.role==="user"?`<button class="danger-btn" type="button" onclick="prepareClear('${encodeURIComponent(u.email)}')">Clear Balance</button>`:"—"}</td></tr>`).join(""):'<tr><td colspan="7">No users found.</td></tr>'}catch(e){userTable.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}
  }
  window.prepareClear=encoded=>{clearEmail.value=decodeURIComponent(encoded);document.querySelector('[data-section="wallets"]')?.click();setTimeout(()=>clearReason.focus(),100);window.scrollTo({top:0,behavior:"smooth"})};
  creditForm.addEventListener("submit",async event=>{event.preventDefault();const email=creditEmail.value.trim().toLowerCase(),amount=Number(creditAmount.value),reason=creditReason.value.trim(),adminPassword=creditAdminPassword.value;if(!confirm(`Credit ${email} with ₦${amount.toLocaleString("en-NG")} for “${reason}”? This will be recorded permanently.`))return;creditButton.disabled=true;creditButton.textContent="Verifying and crediting...";try{const requestId=globalThis.crypto?.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2);await request("/api/wallet/admin/credit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,amount,reason,adminPassword,requestId})});alert("Wallet credited successfully.");creditEmail.value="";creditAdminPassword.value="";await loadWallets();await loadBalances()}catch(e){creditAdminPassword.value="";alert(e.message)}finally{creditButton.disabled=false;creditButton.textContent="Credit Wallet Securely"}});
  clearForm.addEventListener("submit",async event=>{event.preventDefault();const email=clearEmail.value.trim().toLowerCase(),reason=clearReason.value.trim(),adminPassword=clearAdminPassword.value;if(!confirm(`DANGER: Set the entire wallet balance for ${email} to ₦0?\n\nThis action will be recorded and cannot be automatically undone.`))return;clearButton.disabled=true;clearButton.textContent="Verifying and clearing...";try{const requestId=globalThis.crypto?.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2),d=await request("/api/wallet/admin/clear",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,reason,adminPassword,requestId})});alert(`${moneyKobo(d.removedKobo)} was removed. The customer's balance is now ₦0.`);clearForm.reset();await loadWallets();await loadBalances()}catch(e){clearAdminPassword.value="";alert(e.message)}finally{clearButton.disabled=false;clearButton.textContent="Clear Entire Balance Securely"}});
  refresh.addEventListener("click",loadWallets);setTimeout(()=>{loadWallets();loadBalances()},400);
})();
