(function(){
  const $=id=>document.getElementById(id),walletTable=$("adminWalletTable"),refresh=$("refreshWallets"),userTable=$("adminUserTable"),creditForm=$("adminCreditForm"),creditEmail=$("creditEmail"),creditAmount=$("creditAmount"),creditReason=$("creditReason"),creditAdminPassword=$("creditAdminPassword"),creditButton=$("creditButton"),clearForm=$("adminClearForm"),clearEmail=$("clearEmail"),clearReason=$("clearReason"),clearAdminPassword=$("clearAdminPassword"),clearButton=$("clearButton"),manualList=$("manualPaymentList"),manualSearch=$("manualPaymentSearch"),manualFilter=$("manualPaymentFilter"),manualRefresh=$("refreshManualPayments"),manualPending=$("manualPaymentPending"),manualApproved=$("manualPaymentApproved"),manualRejected=$("manualPaymentRejected"),manualValue=$("manualPaymentValue");
  const token=localStorage.getItem("wayneToken"),base=localStorage.getItem("wayneApiUrl")||window.WAYNE_API_URL||"http://localhost:5000";
  const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML},moneyKobo=k=>"₦"+(Number(k||0)/100).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});let walletRows=[];
  function renderWalletResult(message,type="success",title){
    if(!document.getElementById("wayneWalletResultStyle")){
      const style=document.createElement("style");style.id="wayneWalletResultStyle";style.textContent=".wayne-wallet-feedback-layer{position:fixed;inset:0;z-index:2147483646;display:grid;place-items:center;padding:20px;background:rgba(50,50,88,.32);backdrop-filter:blur(9px);-webkit-backdrop-filter:blur(9px)}.wayne-wallet-feedback-card{width:min(430px,calc(100vw - 30px));border:1px solid #ebe9ff;border-radius:30px;background:#fff;color:#232238;box-shadow:0 34px 90px rgba(42,44,88,.28);text-align:center;overflow:hidden;animation:wayneWalletResultIn .24s ease-out}.wayne-wallet-feedback-copy{padding:34px 28px 25px}.wayne-wallet-feedback-icon{display:grid;place-items:center;width:76px;height:76px;margin:0 auto 24px;border:2px solid #bdebd0;border-radius:50%;background:#eafaf1;color:#159552;box-shadow:inset 0 0 0 7px #f8fffb;font-size:31px;font-weight:950}.wayne-wallet-feedback-card.error .wayne-wallet-feedback-icon{border-color:#ffcbd4;background:#fff0f2;color:#db3653;box-shadow:inset 0 0 0 7px #fffafb}.wayne-wallet-feedback-card h2{margin:0 0 12px;color:#232238;font-size:25px;line-height:1.16}.wayne-wallet-feedback-card p{max-width:335px;margin:0 auto;color:#67677f;font-size:16px;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.wayne-wallet-feedback-actions{padding:0 28px 30px}.wayne-wallet-feedback-actions button{width:100%;min-height:56px;border:0;border-radius:15px;background:linear-gradient(135deg,#7768ff,#8d79ff);color:#fff;font-size:16px;font-weight:900;cursor:pointer;box-shadow:0 12px 25px rgba(119,104,255,.25)}@keyframes wayneWalletResultIn{from{opacity:0;transform:translateY(15px) scale(.96)}to{opacity:1;transform:none}}@media(max-width:600px){.wayne-wallet-feedback-card{border-radius:24px}.wayne-wallet-feedback-copy{padding:29px 22px 22px}.wayne-wallet-feedback-icon{width:68px;height:68px;margin-bottom:20px}.wayne-wallet-feedback-card h2{font-size:22px}.wayne-wallet-feedback-card p{font-size:15px}.wayne-wallet-feedback-actions{padding:0 20px 22px}.wayne-wallet-feedback-actions button{min-height:52px}}";document.head.appendChild(style)
    }
    document.querySelector(".wayne-wallet-feedback-layer")?.remove();
    const layer=document.createElement("div");layer.className="wayne-wallet-feedback-layer";
    const card=document.createElement("section");card.className="wayne-wallet-feedback-card "+(type==="error"?"error":"success");card.setAttribute("role","dialog");card.setAttribute("aria-modal","true");
    const copy=document.createElement("div");copy.className="wayne-wallet-feedback-copy";
    const icon=document.createElement("div");icon.className="wayne-wallet-feedback-icon";icon.textContent=type==="error"?"!":"✓";
    const heading=document.createElement("h2");heading.textContent=title||(type==="error"?"Action failed":"Successful");
    const body=document.createElement("p");body.textContent=String(message||"Action completed.");
    copy.append(icon,heading,body);
    const actions=document.createElement("div");actions.className="wayne-wallet-feedback-actions";
    const done=document.createElement("button");done.type="button";done.textContent="Done";done.onclick=()=>layer.remove();
    actions.appendChild(done);card.append(copy,actions);layer.appendChild(card);document.body.appendChild(layer);done.focus()
  }
  function showWalletResult(message,type="success",title){
    let shared=false;
    try{if(typeof window.waynePopup==="function"){window.waynePopup(message,type,title);shared=true}}catch(error){}
    setTimeout(()=>{if(!document.querySelector(".wayne-feedback-layer")&&!document.querySelector(".wayne-wallet-feedback-layer"))renderWalletResult(message,type,title)},shared?80:0)
  }
  function updateClearButton(){const ready=clearEmail.validity.valid&&clearEmail.value.trim()!==""&&clearReason.value.trim().length>=4&&clearAdminPassword.value.length>0;clearButton.disabled=!ready;clearButton.classList.toggle("clear-ready",ready);clearButton.setAttribute("aria-disabled",String(!ready));clearButton.title=ready?"All required information is complete":"Complete the email, reason and admin password first"}
  [clearEmail,clearReason,clearAdminPassword].forEach(input=>input.addEventListener("input",updateClearButton));updateClearButton();
  async function request(path,options={}){options.headers={...(options.headers||{}),Authorization:"Bearer "+token};const r=await fetch(base+path,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
  async function reviewWalletAction(message,title){if(typeof window.wayneConfirm==="function")return await window.wayneConfirm(message,{title,confirmText:"Continue",cancelText:"Recheck"});return window.confirm(message)}
  function renderManualPayments(){if(!manualList)return;const all=walletRows.filter(t=>t.provider==="manual_bank"&&t.type==="deposit"),submitted=all.filter(t=>t.status==="submitted");manualPending.textContent=submitted.length;manualApproved.textContent=all.filter(t=>t.status==="completed").length;manualRejected.textContent=all.filter(t=>t.status==="rejected").length;manualValue.textContent=moneyKobo(submitted.reduce((sum,t)=>sum+Number(t.amountKobo||0),0));const query=manualSearch.value.trim().toLowerCase(),status=manualFilter.value,rows=all.filter(t=>(status==="all"||t.status===status)&&(!query||[t.user?.firstName,t.user?.lastName,t.user?.email,t.reference,t.customerReference].some(value=>String(value||"").toLowerCase().includes(query))));manualList.innerHTML=rows.length?rows.map(t=>{const waiting=t.status==="submitted",name=((t.user?.firstName||"")+" "+(t.user?.lastName||"")).trim()||"Customer";return `<article class="manual-payment-card ${esc(t.status)}"><div class="manual-payment-main"><span class="manual-payment-status ${esc(t.status)}">${waiting?"Waiting for review":t.status==="completed"?"Approved":t.status==="rejected"?"Rejected":"Not submitted"}</span><h3>${esc(name)}</h3><a href="mailto:${esc(t.user?.email||"")}">${esc(t.user?.email||"No email")}</a><small>Submitted ${t.submittedAt?new Date(t.submittedAt).toLocaleString():"not yet"}</small></div><div class="manual-payment-money"><strong>${moneyKobo(t.amountKobo)}</strong><small>Requested amount</small></div><dl><div><dt>WAYNE reference</dt><dd>${esc(t.reference)}</dd></div><div><dt>Customer bank reference</dt><dd>${esc(t.customerReference||"Not supplied")}</dd></div></dl>${waiting?`<div class="manual-payment-actions"><button type="button" class="primary-btn" data-review-payment="${esc(t._id)}" data-decision="approve">✓ Approve & Credit</button><button type="button" class="danger-btn" data-review-payment="${esc(t._id)}" data-decision="reject">✕ Reject</button></div>`:`<div class="manual-payment-result ${esc(t.status)}">${t.status==="completed"?"✓ Wallet credited once":"✕ No wallet credit added"}</div>`}</article>`}).join(""):'<div class="empty">No manual payments match this view.</div>'}
  async function loadWallets(){try{const d=await request("/api/wallet/admin/transactions");walletRows=d.transactions||[];walletTable.innerHTML=walletRows.length?walletRows.map(t=>`<tr><td>${new Date(t.createdAt).toLocaleString()}</td><td>${esc(((t.user?.firstName||"")+" "+(t.user?.lastName||"")).trim())}<br><small>${esc(t.user?.email||"")}</small></td><td>${esc(t.type)}${t.customerReference?`<br><small>Bank ref: ${esc(t.customerReference)}</small>`:""}</td><td>${moneyKobo(t.amountKobo)}</td><td>${esc(t.status)}</td><td>${esc(t.reference)}</td></tr>`).join(""):'<tr><td colspan="6">No wallet transactions.</td></tr>';renderManualPayments()}catch(e){walletTable.innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`;if(manualList)manualList.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  window.reviewTopup=async(id,decision)=>{const approved=await reviewWalletAction(decision==="approve"?"Approve this payment and credit the customer wallet? Recheck the payment details first.":"Reject this payment? No wallet credit will be added.",decision==="approve"?"Review Payment Approval":"Review Payment Rejection");if(!approved)return;const button=document.querySelector(`[data-review-payment="${CSS.escape(String(id))}"][data-decision="${decision}"]`);if(button){button.disabled=true;button.textContent=decision==="approve"?"Approving securely…":"Rejecting…"}try{await request(`/api/wallet/admin/transactions/${encodeURIComponent(id)}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});showWalletResult(decision==="approve"?"Payment approved. The customer's wallet was credited once.":"Payment rejected. No wallet credit was added.","success");await Promise.all([loadWallets(),loadBalances()])}catch(e){if(!e.wayneCancelled)showWalletResult(e.message,"error")}finally{if(button)button.disabled=false}};
  manualList?.addEventListener("click",event=>{const button=event.target.closest("[data-review-payment]");if(button)reviewTopup(button.dataset.reviewPayment,button.dataset.decision)});manualSearch?.addEventListener("input",renderManualPayments);manualFilter?.addEventListener("change",renderManualPayments);manualRefresh?.addEventListener("click",()=>loadWallets().then(()=>showWalletResult("Manual payments refreshed.","success","Payments Refreshed")).catch(e=>showWalletResult(e.message,"error","Refresh Failed")));
  async function loadBalances(){try{const d=await request("/api/auth/admin/users"),rows=d.users||[];userTable.innerHTML=rows.length?rows.map(u=>`<tr><td>${esc(u.firstName+" "+u.lastName)}</td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${moneyKobo(u.walletBalanceKobo)}</td><td>${esc(u.role)}</td><td>${u.isActive?"Active":"Disabled"}</td><td>${u.role==="user"?`<button class="danger-btn" type="button" onclick="prepareClear('${encodeURIComponent(u.email)}')">Clear Balance</button>`:"—"}</td></tr>`).join(""):'<tr><td colspan="7">No users found.</td></tr>'}catch(e){userTable.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
  window.prepareClear=encoded=>{clearEmail.value=decodeURIComponent(encoded);updateClearButton();document.querySelector('[data-section="wallets"]')?.click();setTimeout(()=>clearReason.focus(),100);window.scrollTo({top:0,behavior:"smooth"})};
  creditForm?.addEventListener("submit",async event=>{event.preventDefault();const email=creditEmail.value.trim().toLowerCase(),amount=Number(creditAmount.value),reason=creditReason.value.trim(),adminPassword=creditAdminPassword.value,approved=await reviewWalletAction(`Customer: ${email}\nAmount: ${moneyKobo(amount*100)}\nReason: ${reason}\n\nRecheck the customer and amount before crediting.`,`Review Wallet Credit`);if(!approved)return;creditButton.disabled=true;creditButton.textContent="Verifying and crediting...";try{const requestId=globalThis.crypto?.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2);const result=await request("/api/wallet/admin/credit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,amount,reason,adminPassword,requestId})});showWalletResult(`${moneyKobo(result.transaction?.amountKobo||amount*100)} was added to the customer wallet successfully.`,`success`,`Wallet Credited`);creditEmail.value="";creditAdminPassword.value="";await Promise.all([loadWallets(),loadBalances()])}catch(e){creditAdminPassword.value="";if(!e.wayneCancelled)showWalletResult(e.message,"error")}finally{creditButton.disabled=false;creditButton.textContent="Credit Wallet Securely"}});
  clearForm.addEventListener("submit",async event=>{event.preventDefault();const email=clearEmail.value.trim().toLowerCase(),reason=clearReason.value.trim(),adminPassword=clearAdminPassword.value,approved=await reviewWalletAction(`Customer: ${email}\nReason: ${reason}\n\nThis will remove the entire wallet balance. Recheck before continuing.`,`Review Balance Clearing`);if(!approved)return;clearButton.disabled=true;clearButton.classList.remove("clear-ready");clearButton.textContent="Verifying and clearing...";try{const requestId=globalThis.crypto?.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2),d=await request("/api/wallet/admin/clear",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,reason,adminPassword,requestId})});showWalletResult(`${moneyKobo(d.removedKobo)} was removed. The customer's balance is now ₦0.`,"success");clearForm.reset();updateClearButton();await Promise.all([loadWallets(),loadBalances()])}catch(e){clearAdminPassword.value="";if(!e.wayneCancelled)showWalletResult(e.message,"error")}finally{clearButton.textContent="Clear Entire Balance Securely";updateClearButton()}});
  refresh.addEventListener("click",()=>loadWallets().then(()=>showWalletResult("Wallet records refreshed.","success","Wallets Refreshed")).catch(e=>showWalletResult(e.message,"error","Refresh Failed")));setTimeout(()=>{loadWallets();loadBalances()},400);
})();

