const r=require("express").Router();
const c=require("../controllers/authController");
const{protect,adminOnly}=require("../middleware/authMiddleware");
r.post("/register",c.register);
r.post("/login",c.login);
r.post("/change-password",protect,c.changeTemporaryPassword);
r.get("/me",protect,c.me);
r.get("/admin",protect,adminOnly,(req,res)=>res.json({success:true,user:req.user}));
r.get("/admin/users",protect,adminOnly,c.adminUsers);
r.get("/admin/password-assistance/search",protect,adminOnly,c.adminPasswordSearch);
r.post("/admin/password-assistance/reset",protect,adminOnly,c.adminTemporaryPassword);
module.exports=r;
