const express=require("express");
const cors=require("cors");
const dotenv=require("dotenv");
const morgan=require("morgan");
const mongoose=require("mongoose");
dotenv.config();
const app=express();
const authRoutes=require("./routes/authRoutes");
const productRoutes=require("./routes/productRoutes");
const orderRoutes=require("./routes/orderRoutes");
const walletRoutes=require("./routes/walletRoutes");
const settingRoutes=require("./routes/settingRoutes");
const supportRoutes=require("./routes/supportRoutes");
const notificationRoutes=require("./routes/notificationRoutes");
const{webhook:walletWebhook}=require("./controllers/walletController");
app.disable("x-powered-by");
app.use((req,res,next)=>{res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()");res.setHeader("Cross-Origin-Resource-Policy","same-site");next()});
const allowedOrigins=new Set([process.env.FRONTEND_URL,"https://waynelogs.com","https://www.waynelogs.com","http://localhost:5500","http://127.0.0.1:5500"].concat(String(process.env.ALLOWED_ORIGINS||"").split(",")).map(v=>String(v||"").trim().replace(/\/$/,"")).filter(Boolean));
app.use(cors({origin(origin,callback){if(!origin||allowedOrigins.has(String(origin).replace(/\/$/,"")))return callback(null,true);return callback(new Error("Origin not allowed"))},credentials:false,methods:["GET","POST","PUT","PATCH","DELETE","OPTIONS"],allowedHeaders:["Content-Type","Authorization"]}));
app.use(morgan("dev"));
app.post("/api/wallet/webhooks/:provider",express.raw({type:"application/json",limit:"1mb"}),walletWebhook);
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:true,limit:"2mb"}));
app.use("/api/auth",authRoutes);
app.use("/api/products",productRoutes);
app.use("/api/orders",orderRoutes);
app.use("/api/wallet",walletRoutes);
app.use("/api/settings",settingRoutes);
app.use("/api/support",supportRoutes);
app.use("/api/notifications",notificationRoutes);
app.get("/",(req,res)=>res.json({success:true,message:"WAYNE LOGS MASTER API"}));
app.get("/api/test",(req,res)=>res.json({success:true,message:"Backend online"}));
app.use("/api",(req,res)=>res.status(404).json({message:"API route not found."}));
const PORT=process.env.PORT||5000;
mongoose.connect(process.env.MONGO_URI)
  .then(()=>{console.log("MongoDB connected");app.listen(PORT,()=>console.log("WAYNE LOGS API running on "+PORT));})
  .catch(e=>{console.error("MongoDB connection failed:",e.message);process.exit(1);});
