const nodemailer=require("nodemailer");
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function configured(){return!!(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS)}
function transport(){return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||"").toLowerCase()==="true"||Number(process.env.SMTP_PORT)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS},connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000})}
function money(value){return"₦"+Number(value||0).toLocaleString("en-NG")}
async function send({to,subject,html}){if(!configured()||!to)return{skipped:true};return transport().sendMail({from:process.env.EMAIL_FROM||`WAYNE LOGS <${process.env.SMTP_USER}>`,to,subject,html})}
exports.isConfigured=configured;
exports.sendPurchaseReceipt=({user,order})=>send({to:user.email,subject:`Receipt for ${order.productName} — WAYNE LOGS`,html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#10233d"><div style="padding:22px;border-radius:18px 18px 0 0;background:#10233d;color:#fff"><h1 style="margin:0">WAYNE LOGS</h1><p style="margin:7px 0 0">Payment receipt</p></div><div style="padding:25px;border:1px solid #dbe5ef"><h2>Thank you, ${escapeHtml(user.firstName)}.</h2><p>Your wallet purchase was completed successfully.</p><table style="width:100%;border-collapse:collapse"><tr><td style="padding:10px;border-bottom:1px solid #e5ebf1">Order</td><td style="padding:10px;border-bottom:1px solid #e5ebf1;text-align:right">${escapeHtml(order._id)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #e5ebf1">Product</td><td style="padding:10px;border-bottom:1px solid #e5ebf1;text-align:right">${escapeHtml(order.productName)}</td></tr><tr><td style="padding:10px;border-bottom:1px solid #e5ebf1">Amount</td><td style="padding:10px;border-bottom:1px solid #e5ebf1;text-align:right"><strong>${money(order.totalAmount)}</strong></td></tr><tr><td style="padding:10px">Status</td><td style="padding:10px;text-align:right">${escapeHtml(order.status)}</td></tr></table><p style="margin-top:22px"><a href="${escapeHtml((process.env.FRONTEND_URL||"https://waynelogs.com").replace(/\/$/,""))}/orders.html" style="display:inline-block;padding:12px 18px;border-radius:10px;background:#087fc4;color:#fff;text-decoration:none;font-weight:bold">View Order & Delivery</a></p><p style="font-size:12px;color:#687b93">For security, private delivery information is never included in email. Sign in to view it.</p></div></div>`});
exports.sendLowStockAlert=({product,threshold})=>send({to:process.env.ADMIN_ALERT_EMAIL||process.env.ADMIN_EMAIL,subject:`Low stock: ${product.name} has ${product.stock} left`,html:`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#10233d"><h1>WAYNE LOGS Inventory Alert</h1><div style="padding:20px;border:1px solid #f0c77c;border-radius:15px;background:#fff9ec"><h2 style="margin-top:0">${escapeHtml(product.name)}</h2><p><strong>${Number(product.stock)} unused record${Number(product.stock)===1?"":"s"} remaining.</strong></p><p>The low-stock warning level is ${Number(threshold)}. Open Admin → Inventory to add more records.</p><a href="${escapeHtml((process.env.FRONTEND_URL||"https://waynelogs.com").replace(/\/$/,""))}/admin.html" style="display:inline-block;padding:12px 18px;border-radius:10px;background:#dc7b00;color:#fff;text-decoration:none;font-weight:bold">Open Inventory Manager</a></div></div>`});
