const mongoose=require("mongoose");
const Product=require("../models/Product");
const PUB="name platform type description price currency stock icon color1 color2 status deliveryType createdAt updatedAt";
exports.publicList=async(req,res)=>{try{const products=await Product.find({status:"active"}).select(PUB).sort({createdAt:-1});res.json({success:true,products});}catch(e){res.status(500).json({message:"Could not load products."});}};
exports.publicOne=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const product=await Product.findById(req.params.id).select(PUB);if(!product)return res.status(404).json({message:"Product not found."});res.json({success:true,product});}catch(e){res.status(500).json({message:"Could not load product."});}};
exports.adminList=async(req,res)=>{try{const products=await Product.find().select("+privateDelivery").sort({createdAt:-1});res.json({success:true,products});}catch(e){res.status(500).json({message:"Could not load products."});}};
function body(req){return{name:req.body.name,platform:req.body.platform,type:req.body.type,description:req.body.description||"",price:Number(req.body.price),stock:Number(req.body.stock||0),icon:req.body.icon||"★",color1:req.body.color1||"#7c5cff",color2:req.body.color2||"#ff5db1",status:req.body.status||"active",deliveryType:req.body.deliveryType||"manual",privateDelivery:req.body.privateDelivery||""};}
exports.create=async(req,res)=>{try{const b=body(req);if(!b.name||!b.platform||!["social","vpn"].includes(b.type)||Number.isNaN(b.price)||b.price<0||Number.isNaN(b.stock)||b.stock<0)return res.status(400).json({message:"Check product fields."});const p=await Product.create({...b,createdBy:req.user._id});res.status(201).json({success:true,product:p});}catch(e){res.status(500).json({message:"Could not create product."});}};
exports.update=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const p=await Product.findById(req.params.id).select("+privateDelivery");if(!p)return res.status(404).json({message:"Product not found."});Object.assign(p,body(req));await p.save();res.json({success:true,product:p});}catch(e){res.status(500).json({message:"Could not update product."});}};
exports.remove=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const p=await Product.findById(req.params.id);if(!p)return res.status(404).json({message:"Product not found."});await p.deleteOne();res.json({success:true,message:"Product deleted."});}catch(e){res.status(500).json({message:"Could not delete product."});}};
