const mongoose=require("mongoose");
const Product=require("../models/Product");
const InventoryItem=require("../models/InventoryItem");
const inventoryCrypto=require("../services/inventoryCrypto");
const PUB="name platform type description price currency stock icon color1 color2 status deliveryType createdAt updatedAt";
exports.publicList=async(req,res)=>{try{const products=await Product.find({status:"active"}).select(PUB).sort({createdAt:-1});res.json({success:true,products});}catch(e){res.status(500).json({message:"Could not load products."});}};
exports.publicOne=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const product=await Product.findById(req.params.id).select(PUB);if(!product)return res.status(404).json({message:"Product not found."});res.json({success:true,product});}catch(e){res.status(500).json({message:"Could not load product."});}};
exports.adminList=async(req,res)=>{try{const products=await Product.find().select("+privateDelivery").sort({createdAt:-1});res.json({success:true,products});}catch(e){res.status(500).json({message:"Could not load products."});}};
function lines(req){return[...new Set((Array.isArray(req.body.inventoryItems)?req.body.inventoryItems:[]).map(v=>String(v||"").trim()).filter(Boolean))].slice(0,5000)}
function body(req){return{name:req.body.name,platform:req.body.platform,type:req.body.type,description:req.body.description||"",price:Number(req.body.price),icon:req.body.icon||"★",color1:req.body.color1||"#7c5cff",color2:req.body.color2||"#ff5db1",status:req.body.status||"active",deliveryType:req.body.inventoryManaged?"instant":(req.body.deliveryType||"manual"),inventoryManaged:!!req.body.inventoryManaged,privateDelivery:req.body.privateDelivery||""};}
async function addInventory(product,items){if(!items.length)return 0;const operations=items.map(content=>({updateOne:{filter:{product:product._id,fingerprint:inventoryCrypto.fingerprint(content)},update:{$setOnInsert:{product:product._id,fingerprint:inventoryCrypto.fingerprint(content),encryptedContent:inventoryCrypto.encrypt(content),status:"available"}},upsert:true}}));await InventoryItem.bulkWrite(operations,{ordered:false}).catch(e=>{if(e.code!==11000)throw e});const count=await InventoryItem.countDocuments({product:product._id,status:"available"});product.stock=count;product.inventoryManaged=true;product.deliveryType="instant";await product.save();return count}
exports.create=async(req,res)=>{try{const b=body(req),items=lines(req);if(!b.name||!b.platform||!["social","vpn"].includes(b.type)||Number.isNaN(b.price)||b.price<0)return res.status(400).json({message:"Check product fields."});if(b.inventoryManaged&&!items.length)return res.status(400).json({message:"Paste at least one unique delivery record, one per line."});const p=await Product.create({...b,stock:0,createdBy:req.user._id});if(b.inventoryManaged)await addInventory(p,items);res.status(201).json({success:true,product:p});}catch(e){res.status(500).json({message:e.message||"Could not create product."});}};
exports.update=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const p=await Product.findById(req.params.id).select("+privateDelivery");if(!p)return res.status(404).json({message:"Product not found."});Object.assign(p,body(req));await p.save();if(p.inventoryManaged)await addInventory(p,lines(req));res.json({success:true,product:p});}catch(e){res.status(500).json({message:e.message||"Could not update product."});}};
exports.remove=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const p=await Product.findById(req.params.id);if(!p)return res.status(404).json({message:"Product not found."});await InventoryItem.deleteMany({product:p._id});await p.deleteOne();res.json({success:true,message:"Product deleted."});}catch(e){res.status(500).json({message:"Could not delete product."});}};
exports.inventoryOverview=async(req,res)=>{try{const products=await Product.find({inventoryManaged:true}).select("name platform stock status").sort({name:1});const grouped=await InventoryItem.aggregate([{$group:{_id:{product:"$product",status:"$status"},count:{$sum:1}}}]);const counts=new Map();for(const row of grouped){const id=String(row._id.product),entry=counts.get(id)||{available:0,sold:0};entry[row._id.status]=row.count;counts.set(id,entry)}const inventory=products.map(p=>{const c=counts.get(String(p._id))||{available:0,sold:0};return{id:p._id,name:p.name,platform:p.platform,status:p.status,available:c.available,sold:c.sold,total:c.available+c.sold,lowStock:c.available<=5}});res.json({success:true,inventory,totals:{available:inventory.reduce((s,p)=>s+p.available,0),sold:inventory.reduce((s,p)=>s+p.sold,0),lowStock:inventory.filter(p=>p.lowStock).length}})}catch(e){res.status(500).json({message:"Could not load inventory overview."})}};
exports.inventoryDetail=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const product=await Product.findById(req.params.id).select("name platform stock status inventoryManaged");if(!product)return res.status(404).json({message:"Product not found."});const items=await InventoryItem.find({product:product._id}).select("status soldTo order soldAt createdAt").populate("soldTo","firstName lastName email").sort({createdAt:-1}).limit(500);res.json({success:true,product,items})}catch(e){res.status(500).json({message:"Could not load inventory history."})}};
exports.restock=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid product ID."});const product=await Product.findById(req.params.id);if(!product)return res.status(404).json({message:"Product not found."});const items=lines(req);if(!items.length)return res.status(400).json({message:"Paste at least one new delivery record."});const before=await InventoryItem.countDocuments({product:product._id,status:"available"});const available=await addInventory(product,items);res.json({success:true,added:Math.max(0,available-before),available,duplicates:Math.max(0,items.length-(available-before))})}catch(e){res.status(500).json({message:e.message||"Could not add inventory."})}};
