const mongoose=require("mongoose");
const SupportTicket=require("../models/SupportTicket");
const Order=require("../models/Order");
const notifications=require("../services/notificationService");
function clean(value,max){return String(value||"").trim().slice(0,max)}
exports.create=async(req,res)=>{try{const subject=clean(req.body.subject,120),message=clean(req.body.message,2000),orderId=req.body.orderId||null;if(!subject||message.length<5)return res.status(400).json({message:"Enter a subject and a clear message."});let order=null;if(orderId){if(!mongoose.isValidObjectId(orderId))return res.status(400).json({message:"Invalid order."});order=await Order.findOne({_id:orderId,user:req.user._id});if(!order)return res.status(404).json({message:"Order not found."})}const ticket=await SupportTicket.create({user:req.user._id,order:order?._id||null,subject,message});res.status(201).json({success:true,ticket})}catch(e){res.status(500).json({message:"Could not create support ticket."})}};
exports.mine=async(req,res)=>{try{const tickets=await SupportTicket.find({user:req.user._id}).populate("order","productName status paymentStatus").populate("replies.sender","firstName lastName").sort({lastReplyAt:-1});res.json({success:true,tickets})}catch(e){res.status(500).json({message:"Could not load support tickets."})}};
exports.customerReply=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid ticket."});const message=clean(req.body.message,2000);if(message.length<2)return res.status(400).json({message:"Enter a reply."});const ticket=await SupportTicket.findOne({_id:req.params.id,user:req.user._id});if(!ticket)return res.status(404).json({message:"Ticket not found."});ticket.replies.push({sender:req.user._id,role:"customer",message});ticket.status="open";ticket.lastReplyAt=new Date();await ticket.save();res.json({success:true,ticket})}catch(e){res.status(500).json({message:"Could not send reply."})}};
exports.adminAll=async(req,res)=>{try{const tickets=await SupportTicket.find().populate("user","firstName lastName email phone").populate("order","productName status paymentStatus").populate("replies.sender","firstName lastName").sort({lastReplyAt:-1});res.json({success:true,tickets})}catch(e){res.status(500).json({message:"Could not load support tickets."})}};
exports.adminReply=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid ticket."});const message=clean(req.body.message,2000);if(message.length<2)return res.status(400).json({message:"Enter a reply."});const ticket=await SupportTicket.findById(req.params.id);if(!ticket)return res.status(404).json({message:"Ticket not found."});ticket.replies.push({sender:req.user._id,role:"admin",message});ticket.status=req.body.resolve?"resolved":"in_progress";ticket.lastReplyAt=new Date();await ticket.save();const reply=ticket.replies[ticket.replies.length-1];await notifications.create({user:ticket.user,type:"support",title:"New support reply",message:`WAYNE LOGS replied to: ${ticket.subject}`,link:`support.html`,key:`support:${ticket._id}:${reply._id}`});res.json({success:true,ticket})}catch(e){res.status(500).json({message:"Could not send admin reply."})}};
exports.adminStatus=async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:"Invalid ticket."});const status=req.body.status;if(!["open","in_progress","resolved"].includes(status))return res.status(400).json({message:"Invalid ticket status."});const ticket=await SupportTicket.findByIdAndUpdate(req.params.id,{$set:{status,lastReplyAt:new Date()}},{new:true});if(!ticket)return res.status(404).json({message:"Ticket not found."});res.json({success:true,ticket})}catch(e){res.status(500).json({message:"Could not update ticket."})}};
